/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CreateSinglePlayerGame201ResponseRoundsInner } from './CreateSinglePlayerGame201ResponseRoundsInner'
import {
  CreateSinglePlayerGame201ResponseRoundsInnerFromJSON,
  CreateSinglePlayerGame201ResponseRoundsInnerFromJSONTyped,
  CreateSinglePlayerGame201ResponseRoundsInnerToJSON,
  CreateSinglePlayerGame201ResponseRoundsInnerToJSONTyped,
} from './CreateSinglePlayerGame201ResponseRoundsInner'

/**
 *
 * @export
 * @interface CreateSinglePlayerGame201Response
 */
export interface CreateSinglePlayerGame201Response {
  /**
   *
   * @type {string}
   * @memberof CreateSinglePlayerGame201Response
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof CreateSinglePlayerGame201Response
   */
  status: CreateSinglePlayerGame201ResponseStatusEnum
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGame201Response
   */
  currentRound: number
  /**
   *
   * @type {Array<CreateSinglePlayerGame201ResponseRoundsInner>}
   * @memberof CreateSinglePlayerGame201Response
   */
  rounds: Array<CreateSinglePlayerGame201ResponseRoundsInner>
  /**
   *
   * @type {Date}
   * @memberof CreateSinglePlayerGame201Response
   */
  createdAt: Date
  /**
   *
   * @type {Date}
   * @memberof CreateSinglePlayerGame201Response
   */
  completedAt?: Date
}

/**
 * @export
 */
export const CreateSinglePlayerGame201ResponseStatusEnum = {
  Ongoing: 'ongoing',
  Completed: 'completed',
} as const
export type CreateSinglePlayerGame201ResponseStatusEnum =
  (typeof CreateSinglePlayerGame201ResponseStatusEnum)[keyof typeof CreateSinglePlayerGame201ResponseStatusEnum]

/**
 * Check if a given object implements the CreateSinglePlayerGame201Response interface.
 */
export function instanceOfCreateSinglePlayerGame201Response(
  value: object,
): value is CreateSinglePlayerGame201Response {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('status' in value) || value['status'] === undefined) return false
  if (!('currentRound' in value) || value['currentRound'] === undefined) return false
  if (!('rounds' in value) || value['rounds'] === undefined) return false
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false
  return true
}

export function CreateSinglePlayerGame201ResponseFromJSON(
  json: any,
): CreateSinglePlayerGame201Response {
  return CreateSinglePlayerGame201ResponseFromJSONTyped(json, false)
}

export function CreateSinglePlayerGame201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSinglePlayerGame201Response {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    status: json['status'],
    currentRound: json['currentRound'],
    rounds: (json['rounds'] as Array<any>).map(
      CreateSinglePlayerGame201ResponseRoundsInnerFromJSON,
    ),
    createdAt: new Date(json['createdAt']),
    completedAt: json['completedAt'] == null ? undefined : new Date(json['completedAt']),
  }
}

export function CreateSinglePlayerGame201ResponseToJSON(
  json: any,
): CreateSinglePlayerGame201Response {
  return CreateSinglePlayerGame201ResponseToJSONTyped(json, false)
}

export function CreateSinglePlayerGame201ResponseToJSONTyped(
  value?: CreateSinglePlayerGame201Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    status: value['status'],
    currentRound: value['currentRound'],
    rounds: (value['rounds'] as Array<any>).map(CreateSinglePlayerGame201ResponseRoundsInnerToJSON),
    createdAt: value['createdAt'].toISOString(),
    completedAt:
      value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
  }
}
