/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateWithFriendsGameGuessRequestGuess
 */
export interface CreateWithFriendsGameGuessRequestGuess {
  /**
   *
   * @type {number}
   * @memberof CreateWithFriendsGameGuessRequestGuess
   */
  latitude: number
  /**
   *
   * @type {number}
   * @memberof CreateWithFriendsGameGuessRequestGuess
   */
  longitude: number
}

/**
 * Check if a given object implements the CreateWithFriendsGameGuessRequestGuess interface.
 */
export function instanceOfCreateWithFriendsGameGuessRequestGuess(
  value: object,
): value is CreateWithFriendsGameGuessRequestGuess {
  if (!('latitude' in value) || value['latitude'] === undefined) return false
  if (!('longitude' in value) || value['longitude'] === undefined) return false
  return true
}

export function CreateWithFriendsGameGuessRequestGuessFromJSON(
  json: any,
): CreateWithFriendsGameGuessRequestGuess {
  return CreateWithFriendsGameGuessRequestGuessFromJSONTyped(json, false)
}

export function CreateWithFriendsGameGuessRequestGuessFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateWithFriendsGameGuessRequestGuess {
  if (json == null) {
    return json
  }
  return {
    latitude: json['latitude'],
    longitude: json['longitude'],
  }
}

export function CreateWithFriendsGameGuessRequestGuessToJSON(
  json: any,
): CreateWithFriendsGameGuessRequestGuess {
  return CreateWithFriendsGameGuessRequestGuessToJSONTyped(json, false)
}

export function CreateWithFriendsGameGuessRequestGuessToJSONTyped(
  value?: CreateWithFriendsGameGuessRequestGuess | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    latitude: value['latitude'],
    longitude: value['longitude'],
  }
}
