/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateWithFriendsGameResponse
 */
export interface CreateWithFriendsGameResponse {
  /**
   *
   * @type {string}
   * @memberof CreateWithFriendsGameResponse
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof CreateWithFriendsGameResponse
   */
  roomKey: string
}

/**
 * Check if a given object implements the CreateWithFriendsGameResponse interface.
 */
export function instanceOfCreateWithFriendsGameResponse(
  value: object,
): value is CreateWithFriendsGameResponse {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('roomKey' in value) || value['roomKey'] === undefined) return false
  return true
}

export function CreateWithFriendsGameResponseFromJSON(json: any): CreateWithFriendsGameResponse {
  return CreateWithFriendsGameResponseFromJSONTyped(json, false)
}

export function CreateWithFriendsGameResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateWithFriendsGameResponse {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    roomKey: json['roomKey'],
  }
}

export function CreateWithFriendsGameResponseToJSON(json: any): CreateWithFriendsGameResponse {
  return CreateWithFriendsGameResponseToJSONTyped(json, false)
}

export function CreateWithFriendsGameResponseToJSONTyped(
  value?: CreateWithFriendsGameResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    roomKey: value['roomKey'],
  }
}
