/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CreateSinglePlayerGame201ResponseRoundsInnerResultTarget } from './CreateSinglePlayerGame201ResponseRoundsInnerResultTarget'
import {
  CreateSinglePlayerGame201ResponseRoundsInnerResultTargetFromJSON,
  CreateSinglePlayerGame201ResponseRoundsInnerResultTargetFromJSONTyped,
  CreateSinglePlayerGame201ResponseRoundsInnerResultTargetToJSON,
  CreateSinglePlayerGame201ResponseRoundsInnerResultTargetToJSONTyped,
} from './CreateSinglePlayerGame201ResponseRoundsInnerResultTarget'
import type { CreateSinglePlayerGame201ResponseRoundsInnerResultGuess } from './CreateSinglePlayerGame201ResponseRoundsInnerResultGuess'
import {
  CreateSinglePlayerGame201ResponseRoundsInnerResultGuessFromJSON,
  CreateSinglePlayerGame201ResponseRoundsInnerResultGuessFromJSONTyped,
  CreateSinglePlayerGame201ResponseRoundsInnerResultGuessToJSON,
  CreateSinglePlayerGame201ResponseRoundsInnerResultGuessToJSONTyped,
} from './CreateSinglePlayerGame201ResponseRoundsInnerResultGuess'

/**
 *
 * @export
 * @interface CreateSinglePlayerGame201ResponseRoundsInnerResult
 */
export interface CreateSinglePlayerGame201ResponseRoundsInnerResult {
  /**
   *
   * @type {CreateSinglePlayerGame201ResponseRoundsInnerResultGuess}
   * @memberof CreateSinglePlayerGame201ResponseRoundsInnerResult
   */
  guess: CreateSinglePlayerGame201ResponseRoundsInnerResultGuess | null
  /**
   *
   * @type {CreateSinglePlayerGame201ResponseRoundsInnerResultTarget}
   * @memberof CreateSinglePlayerGame201ResponseRoundsInnerResult
   */
  target: CreateSinglePlayerGame201ResponseRoundsInnerResultTarget
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGame201ResponseRoundsInnerResult
   */
  distanceKm: number
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGame201ResponseRoundsInnerResult
   */
  score: number
  /**
   *
   * @type {Date}
   * @memberof CreateSinglePlayerGame201ResponseRoundsInnerResult
   */
  completedAt: Date
}

/**
 * Check if a given object implements the CreateSinglePlayerGame201ResponseRoundsInnerResult interface.
 */
export function instanceOfCreateSinglePlayerGame201ResponseRoundsInnerResult(
  value: object,
): value is CreateSinglePlayerGame201ResponseRoundsInnerResult {
  if (!('guess' in value) || value['guess'] === undefined) return false
  if (!('target' in value) || value['target'] === undefined) return false
  if (!('distanceKm' in value) || value['distanceKm'] === undefined) return false
  if (!('score' in value) || value['score'] === undefined) return false
  if (!('completedAt' in value) || value['completedAt'] === undefined) return false
  return true
}

export function CreateSinglePlayerGame201ResponseRoundsInnerResultFromJSON(
  json: any,
): CreateSinglePlayerGame201ResponseRoundsInnerResult {
  return CreateSinglePlayerGame201ResponseRoundsInnerResultFromJSONTyped(json, false)
}

export function CreateSinglePlayerGame201ResponseRoundsInnerResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSinglePlayerGame201ResponseRoundsInnerResult {
  if (json == null) {
    return json
  }
  return {
    guess: CreateSinglePlayerGame201ResponseRoundsInnerResultGuessFromJSON(json['guess']),
    target: CreateSinglePlayerGame201ResponseRoundsInnerResultTargetFromJSON(json['target']),
    distanceKm: json['distanceKm'],
    score: json['score'],
    completedAt: new Date(json['completedAt']),
  }
}

export function CreateSinglePlayerGame201ResponseRoundsInnerResultToJSON(
  json: any,
): CreateSinglePlayerGame201ResponseRoundsInnerResult {
  return CreateSinglePlayerGame201ResponseRoundsInnerResultToJSONTyped(json, false)
}

export function CreateSinglePlayerGame201ResponseRoundsInnerResultToJSONTyped(
  value?: CreateSinglePlayerGame201ResponseRoundsInnerResult | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    guess: CreateSinglePlayerGame201ResponseRoundsInnerResultGuessToJSON(value['guess']),
    target: CreateSinglePlayerGame201ResponseRoundsInnerResultTargetToJSON(value['target']),
    distanceKm: value['distanceKm'],
    score: value['score'],
    completedAt: value['completedAt'].toISOString(),
  }
}
