/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateSinglePlayerGameGuess200ResponseResultTarget
 */
export interface CreateSinglePlayerGameGuess200ResponseResultTarget {
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGameGuess200ResponseResultTarget
   */
  latitude: number
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGameGuess200ResponseResultTarget
   */
  longitude: number
}

/**
 * Check if a given object implements the CreateSinglePlayerGameGuess200ResponseResultTarget interface.
 */
export function instanceOfCreateSinglePlayerGameGuess200ResponseResultTarget(
  value: object,
): value is CreateSinglePlayerGameGuess200ResponseResultTarget {
  if (!('latitude' in value) || value['latitude'] === undefined) return false
  if (!('longitude' in value) || value['longitude'] === undefined) return false
  return true
}

export function CreateSinglePlayerGameGuess200ResponseResultTargetFromJSON(
  json: any,
): CreateSinglePlayerGameGuess200ResponseResultTarget {
  return CreateSinglePlayerGameGuess200ResponseResultTargetFromJSONTyped(json, false)
}

export function CreateSinglePlayerGameGuess200ResponseResultTargetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSinglePlayerGameGuess200ResponseResultTarget {
  if (json == null) {
    return json
  }
  return {
    latitude: json['latitude'],
    longitude: json['longitude'],
  }
}

export function CreateSinglePlayerGameGuess200ResponseResultTargetToJSON(
  json: any,
): CreateSinglePlayerGameGuess200ResponseResultTarget {
  return CreateSinglePlayerGameGuess200ResponseResultTargetToJSONTyped(json, false)
}

export function CreateSinglePlayerGameGuess200ResponseResultTargetToJSONTyped(
  value?: CreateSinglePlayerGameGuess200ResponseResultTarget | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    latitude: value['latitude'],
    longitude: value['longitude'],
  }
}
