/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CreateSinglePlayerGameGuessRequestGuess } from './CreateSinglePlayerGameGuessRequestGuess'
import {
  CreateSinglePlayerGameGuessRequestGuessFromJSON,
  CreateSinglePlayerGameGuessRequestGuessFromJSONTyped,
  CreateSinglePlayerGameGuessRequestGuessToJSON,
  CreateSinglePlayerGameGuessRequestGuessToJSONTyped,
} from './CreateSinglePlayerGameGuessRequestGuess'

/**
 *
 * @export
 * @interface CreateSinglePlayerGameGuessRequest
 */
export interface CreateSinglePlayerGameGuessRequest {
  /**
   *
   * @type {CreateSinglePlayerGameGuessRequestGuess}
   * @memberof CreateSinglePlayerGameGuessRequest
   */
  guess: CreateSinglePlayerGameGuessRequestGuess | null
}

/**
 * Check if a given object implements the CreateSinglePlayerGameGuessRequest interface.
 */
export function instanceOfCreateSinglePlayerGameGuessRequest(
  value: object,
): value is CreateSinglePlayerGameGuessRequest {
  if (!('guess' in value) || value['guess'] === undefined) return false
  return true
}

export function CreateSinglePlayerGameGuessRequestFromJSON(
  json: any,
): CreateSinglePlayerGameGuessRequest {
  return CreateSinglePlayerGameGuessRequestFromJSONTyped(json, false)
}

export function CreateSinglePlayerGameGuessRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSinglePlayerGameGuessRequest {
  if (json == null) {
    return json
  }
  return {
    guess: CreateSinglePlayerGameGuessRequestGuessFromJSON(json['guess']),
  }
}

export function CreateSinglePlayerGameGuessRequestToJSON(
  json: any,
): CreateSinglePlayerGameGuessRequest {
  return CreateSinglePlayerGameGuessRequestToJSONTyped(json, false)
}

export function CreateSinglePlayerGameGuessRequestToJSONTyped(
  value?: CreateSinglePlayerGameGuessRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    guess: CreateSinglePlayerGameGuessRequestGuessToJSON(value['guess']),
  }
}
