/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateSinglePlayerGameGuessCoordinate
 */
export interface CreateSinglePlayerGameGuessCoordinate {
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGameGuessCoordinate
   */
  latitude: number
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGameGuessCoordinate
   */
  longitude: number
}

/**
 * Check if a given object implements the CreateSinglePlayerGameGuessCoordinate interface.
 */
export function instanceOfCreateSinglePlayerGameGuessCoordinate(
  value: object,
): value is CreateSinglePlayerGameGuessCoordinate {
  if (!('latitude' in value) || value['latitude'] === undefined) return false
  if (!('longitude' in value) || value['longitude'] === undefined) return false
  return true
}

export function CreateSinglePlayerGameGuessCoordinateFromJSON(
  json: any,
): CreateSinglePlayerGameGuessCoordinate {
  return CreateSinglePlayerGameGuessCoordinateFromJSONTyped(json, false)
}

export function CreateSinglePlayerGameGuessCoordinateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSinglePlayerGameGuessCoordinate {
  if (json == null) {
    return json
  }
  return {
    latitude: json['latitude'],
    longitude: json['longitude'],
  }
}

export function CreateSinglePlayerGameGuessCoordinateToJSON(
  json: any,
): CreateSinglePlayerGameGuessCoordinate {
  return CreateSinglePlayerGameGuessCoordinateToJSONTyped(json, false)
}

export function CreateSinglePlayerGameGuessCoordinateToJSONTyped(
  value?: CreateSinglePlayerGameGuessCoordinate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    latitude: value['latitude'],
    longitude: value['longitude'],
  }
}
