/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CreateSinglePlayerGame201ResponseRoundsInnerResult } from './CreateSinglePlayerGame201ResponseRoundsInnerResult'
import {
  CreateSinglePlayerGame201ResponseRoundsInnerResultFromJSON,
  CreateSinglePlayerGame201ResponseRoundsInnerResultFromJSONTyped,
  CreateSinglePlayerGame201ResponseRoundsInnerResultToJSON,
  CreateSinglePlayerGame201ResponseRoundsInnerResultToJSONTyped,
} from './CreateSinglePlayerGame201ResponseRoundsInnerResult'

/**
 *
 * @export
 * @interface CreateSinglePlayerGame201ResponseRoundsInner
 */
export interface CreateSinglePlayerGame201ResponseRoundsInner {
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGame201ResponseRoundsInner
   */
  roundNumber: number
  /**
   *
   * @type {string}
   * @memberof CreateSinglePlayerGame201ResponseRoundsInner
   */
  imageId: string
  /**
   *
   * @type {Date}
   * @memberof CreateSinglePlayerGame201ResponseRoundsInner
   */
  startedAt: Date
  /**
   *
   * @type {CreateSinglePlayerGame201ResponseRoundsInnerResult}
   * @memberof CreateSinglePlayerGame201ResponseRoundsInner
   */
  result?: CreateSinglePlayerGame201ResponseRoundsInnerResult
}

/**
 * Check if a given object implements the CreateSinglePlayerGame201ResponseRoundsInner interface.
 */
export function instanceOfCreateSinglePlayerGame201ResponseRoundsInner(
  value: object,
): value is CreateSinglePlayerGame201ResponseRoundsInner {
  if (!('roundNumber' in value) || value['roundNumber'] === undefined) return false
  if (!('imageId' in value) || value['imageId'] === undefined) return false
  if (!('startedAt' in value) || value['startedAt'] === undefined) return false
  return true
}

export function CreateSinglePlayerGame201ResponseRoundsInnerFromJSON(
  json: any,
): CreateSinglePlayerGame201ResponseRoundsInner {
  return CreateSinglePlayerGame201ResponseRoundsInnerFromJSONTyped(json, false)
}

export function CreateSinglePlayerGame201ResponseRoundsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSinglePlayerGame201ResponseRoundsInner {
  if (json == null) {
    return json
  }
  return {
    roundNumber: json['roundNumber'],
    imageId: json['imageId'],
    startedAt: new Date(json['startedAt']),
    result:
      json['result'] == null
        ? undefined
        : CreateSinglePlayerGame201ResponseRoundsInnerResultFromJSON(json['result']),
  }
}

export function CreateSinglePlayerGame201ResponseRoundsInnerToJSON(
  json: any,
): CreateSinglePlayerGame201ResponseRoundsInner {
  return CreateSinglePlayerGame201ResponseRoundsInnerToJSONTyped(json, false)
}

export function CreateSinglePlayerGame201ResponseRoundsInnerToJSONTyped(
  value?: CreateSinglePlayerGame201ResponseRoundsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    roundNumber: value['roundNumber'],
    imageId: value['imageId'],
    startedAt: value['startedAt'].toISOString(),
    result: CreateSinglePlayerGame201ResponseRoundsInnerResultToJSON(value['result']),
  }
}
