/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CreateSinglePlayerGameGuess200ResponseResult } from './CreateSinglePlayerGameGuess200ResponseResult'
import {
  CreateSinglePlayerGameGuess200ResponseResultFromJSON,
  CreateSinglePlayerGameGuess200ResponseResultFromJSONTyped,
  CreateSinglePlayerGameGuess200ResponseResultToJSON,
  CreateSinglePlayerGameGuess200ResponseResultToJSONTyped,
} from './CreateSinglePlayerGameGuess200ResponseResult'

/**
 *
 * @export
 * @interface CreateDailyChallengeGameGuessResponse
 */
export interface CreateDailyChallengeGameGuessResponse {
  /**
   *
   * @type {number}
   * @memberof CreateDailyChallengeGameGuessResponse
   */
  roundNumber: number
  /**
   *
   * @type {string}
   * @memberof CreateDailyChallengeGameGuessResponse
   */
  imageId: string
  /**
   *
   * @type {Date}
   * @memberof CreateDailyChallengeGameGuessResponse
   */
  startedAt: Date
  /**
   *
   * @type {CreateSinglePlayerGameGuess200ResponseResult}
   * @memberof CreateDailyChallengeGameGuessResponse
   */
  result: CreateSinglePlayerGameGuess200ResponseResult
}

/**
 * Check if a given object implements the CreateDailyChallengeGameGuessResponse interface.
 */
export function instanceOfCreateDailyChallengeGameGuessResponse(
  value: object,
): value is CreateDailyChallengeGameGuessResponse {
  if (!('roundNumber' in value) || value['roundNumber'] === undefined) return false
  if (!('imageId' in value) || value['imageId'] === undefined) return false
  if (!('startedAt' in value) || value['startedAt'] === undefined) return false
  if (!('result' in value) || value['result'] === undefined) return false
  return true
}

export function CreateDailyChallengeGameGuessResponseFromJSON(
  json: any,
): CreateDailyChallengeGameGuessResponse {
  return CreateDailyChallengeGameGuessResponseFromJSONTyped(json, false)
}

export function CreateDailyChallengeGameGuessResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateDailyChallengeGameGuessResponse {
  if (json == null) {
    return json
  }
  return {
    roundNumber: json['roundNumber'],
    imageId: json['imageId'],
    startedAt: new Date(json['startedAt']),
    result: CreateSinglePlayerGameGuess200ResponseResultFromJSON(json['result']),
  }
}

export function CreateDailyChallengeGameGuessResponseToJSON(
  json: any,
): CreateDailyChallengeGameGuessResponse {
  return CreateDailyChallengeGameGuessResponseToJSONTyped(json, false)
}

export function CreateDailyChallengeGameGuessResponseToJSONTyped(
  value?: CreateDailyChallengeGameGuessResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    roundNumber: value['roundNumber'],
    imageId: value['imageId'],
    startedAt: value['startedAt'].toISOString(),
    result: CreateSinglePlayerGameGuess200ResponseResultToJSON(value['result']),
  }
}
