/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CreateSinglePlayerGameGuessRequestGuess } from './CreateSinglePlayerGameGuessRequestGuess'
import {
  CreateSinglePlayerGameGuessRequestGuessFromJSON,
  CreateSinglePlayerGameGuessRequestGuessFromJSONTyped,
  CreateSinglePlayerGameGuessRequestGuessToJSON,
  CreateSinglePlayerGameGuessRequestGuessToJSONTyped,
} from './CreateSinglePlayerGameGuessRequestGuess'

/**
 *
 * @export
 * @interface CreateDailyChallengeGameGuessRequest
 */
export interface CreateDailyChallengeGameGuessRequest {
  /**
   *
   * @type {CreateSinglePlayerGameGuessRequestGuess}
   * @memberof CreateDailyChallengeGameGuessRequest
   */
  guess: CreateSinglePlayerGameGuessRequestGuess | null
}

/**
 * Check if a given object implements the CreateDailyChallengeGameGuessRequest interface.
 */
export function instanceOfCreateDailyChallengeGameGuessRequest(
  value: object,
): value is CreateDailyChallengeGameGuessRequest {
  if (!('guess' in value) || value['guess'] === undefined) return false
  return true
}

export function CreateDailyChallengeGameGuessRequestFromJSON(
  json: any,
): CreateDailyChallengeGameGuessRequest {
  return CreateDailyChallengeGameGuessRequestFromJSONTyped(json, false)
}

export function CreateDailyChallengeGameGuessRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateDailyChallengeGameGuessRequest {
  if (json == null) {
    return json
  }
  return {
    guess: CreateSinglePlayerGameGuessRequestGuessFromJSON(json['guess']),
  }
}

export function CreateDailyChallengeGameGuessRequestToJSON(
  json: any,
): CreateDailyChallengeGameGuessRequest {
  return CreateDailyChallengeGameGuessRequestToJSONTyped(json, false)
}

export function CreateDailyChallengeGameGuessRequestToJSONTyped(
  value?: CreateDailyChallengeGameGuessRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    guess: CreateSinglePlayerGameGuessRequestGuessToJSON(value['guess']),
  }
}
