/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CreateSinglePlayerGameGuess200ResponseResult } from './CreateSinglePlayerGameGuess200ResponseResult'
import {
  CreateSinglePlayerGameGuess200ResponseResultFromJSON,
  CreateSinglePlayerGameGuess200ResponseResultFromJSONTyped,
  CreateSinglePlayerGameGuess200ResponseResultToJSON,
  CreateSinglePlayerGameGuess200ResponseResultToJSONTyped,
} from './CreateSinglePlayerGameGuess200ResponseResult'

/**
 *
 * @export
 * @interface CreateSinglePlayerGameResponseRoundsInner
 */
export interface CreateSinglePlayerGameResponseRoundsInner {
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGameResponseRoundsInner
   */
  roundNumber: number
  /**
   *
   * @type {string}
   * @memberof CreateSinglePlayerGameResponseRoundsInner
   */
  imageId: string
  /**
   *
   * @type {Date}
   * @memberof CreateSinglePlayerGameResponseRoundsInner
   */
  startedAt: Date
  /**
   *
   * @type {CreateSinglePlayerGameGuess200ResponseResult}
   * @memberof CreateSinglePlayerGameResponseRoundsInner
   */
  result?: CreateSinglePlayerGameGuess200ResponseResult
}

/**
 * Check if a given object implements the CreateSinglePlayerGameResponseRoundsInner interface.
 */
export function instanceOfCreateSinglePlayerGameResponseRoundsInner(
  value: object,
): value is CreateSinglePlayerGameResponseRoundsInner {
  if (!('roundNumber' in value) || value['roundNumber'] === undefined) return false
  if (!('imageId' in value) || value['imageId'] === undefined) return false
  if (!('startedAt' in value) || value['startedAt'] === undefined) return false
  return true
}

export function CreateSinglePlayerGameResponseRoundsInnerFromJSON(
  json: any,
): CreateSinglePlayerGameResponseRoundsInner {
  return CreateSinglePlayerGameResponseRoundsInnerFromJSONTyped(json, false)
}

export function CreateSinglePlayerGameResponseRoundsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSinglePlayerGameResponseRoundsInner {
  if (json == null) {
    return json
  }
  return {
    roundNumber: json['roundNumber'],
    imageId: json['imageId'],
    startedAt: new Date(json['startedAt']),
    result:
      json['result'] == null
        ? undefined
        : CreateSinglePlayerGameGuess200ResponseResultFromJSON(json['result']),
  }
}

export function CreateSinglePlayerGameResponseRoundsInnerToJSON(
  json: any,
): CreateSinglePlayerGameResponseRoundsInner {
  return CreateSinglePlayerGameResponseRoundsInnerToJSONTyped(json, false)
}

export function CreateSinglePlayerGameResponseRoundsInnerToJSONTyped(
  value?: CreateSinglePlayerGameResponseRoundsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    roundNumber: value['roundNumber'],
    imageId: value['imageId'],
    startedAt: value['startedAt'].toISOString(),
    result: CreateSinglePlayerGameGuess200ResponseResultToJSON(value['result']),
  }
}
