/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CreateDailyChallengeGame200ResponseRoundsInner } from './CreateDailyChallengeGame200ResponseRoundsInner'
import {
  CreateDailyChallengeGame200ResponseRoundsInnerFromJSON,
  CreateDailyChallengeGame200ResponseRoundsInnerFromJSONTyped,
  CreateDailyChallengeGame200ResponseRoundsInnerToJSON,
  CreateDailyChallengeGame200ResponseRoundsInnerToJSONTyped,
} from './CreateDailyChallengeGame200ResponseRoundsInner'

/**
 *
 * @export
 * @interface CreateDailyChallengeGameResponse
 */
export interface CreateDailyChallengeGameResponse {
  /**
   *
   * @type {string}
   * @memberof CreateDailyChallengeGameResponse
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof CreateDailyChallengeGameResponse
   */
  status: CreateDailyChallengeGameResponseStatusEnum
  /**
   *
   * @type {number}
   * @memberof CreateDailyChallengeGameResponse
   */
  currentRound: number
  /**
   *
   * @type {Array<CreateDailyChallengeGame200ResponseRoundsInner>}
   * @memberof CreateDailyChallengeGameResponse
   */
  rounds: Array<CreateDailyChallengeGame200ResponseRoundsInner>
  /**
   *
   * @type {Date}
   * @memberof CreateDailyChallengeGameResponse
   */
  createdAt: Date
  /**
   *
   * @type {Date}
   * @memberof CreateDailyChallengeGameResponse
   */
  completedAt?: Date
}

/**
 * @export
 */
export const CreateDailyChallengeGameResponseStatusEnum = {
  Ongoing: 'ongoing',
  Completed: 'completed',
} as const
export type CreateDailyChallengeGameResponseStatusEnum =
  (typeof CreateDailyChallengeGameResponseStatusEnum)[keyof typeof CreateDailyChallengeGameResponseStatusEnum]

/**
 * Check if a given object implements the CreateDailyChallengeGameResponse interface.
 */
export function instanceOfCreateDailyChallengeGameResponse(
  value: object,
): value is CreateDailyChallengeGameResponse {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('status' in value) || value['status'] === undefined) return false
  if (!('currentRound' in value) || value['currentRound'] === undefined) return false
  if (!('rounds' in value) || value['rounds'] === undefined) return false
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false
  return true
}

export function CreateDailyChallengeGameResponseFromJSON(
  json: any,
): CreateDailyChallengeGameResponse {
  return CreateDailyChallengeGameResponseFromJSONTyped(json, false)
}

export function CreateDailyChallengeGameResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateDailyChallengeGameResponse {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    status: json['status'],
    currentRound: json['currentRound'],
    rounds: (json['rounds'] as Array<any>).map(
      CreateDailyChallengeGame200ResponseRoundsInnerFromJSON,
    ),
    createdAt: new Date(json['createdAt']),
    completedAt: json['completedAt'] == null ? undefined : new Date(json['completedAt']),
  }
}

export function CreateDailyChallengeGameResponseToJSON(
  json: any,
): CreateDailyChallengeGameResponse {
  return CreateDailyChallengeGameResponseToJSONTyped(json, false)
}

export function CreateDailyChallengeGameResponseToJSONTyped(
  value?: CreateDailyChallengeGameResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    status: value['status'],
    currentRound: value['currentRound'],
    rounds: (value['rounds'] as Array<any>).map(
      CreateDailyChallengeGame200ResponseRoundsInnerToJSON,
    ),
    createdAt: value['createdAt'].toISOString(),
    completedAt:
      value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
  }
}
