/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CreateSinglePlayerGameGuess200ResponseResult } from './CreateSinglePlayerGameGuess200ResponseResult'
import {
  CreateSinglePlayerGameGuess200ResponseResultFromJSON,
  CreateSinglePlayerGameGuess200ResponseResultFromJSONTyped,
  CreateSinglePlayerGameGuess200ResponseResultToJSON,
  CreateSinglePlayerGameGuess200ResponseResultToJSONTyped,
} from './CreateSinglePlayerGameGuess200ResponseResult'

/**
 *
 * @export
 * @interface CreateDailyChallengeGameGuess200Response
 */
export interface CreateDailyChallengeGameGuess200Response {
  /**
   *
   * @type {number}
   * @memberof CreateDailyChallengeGameGuess200Response
   */
  roundNumber: number
  /**
   *
   * @type {string}
   * @memberof CreateDailyChallengeGameGuess200Response
   */
  imageId: string
  /**
   *
   * @type {Date}
   * @memberof CreateDailyChallengeGameGuess200Response
   */
  startedAt: Date
  /**
   *
   * @type {CreateSinglePlayerGameGuess200ResponseResult}
   * @memberof CreateDailyChallengeGameGuess200Response
   */
  result: CreateSinglePlayerGameGuess200ResponseResult
}

/**
 * Check if a given object implements the CreateDailyChallengeGameGuess200Response interface.
 */
export function instanceOfCreateDailyChallengeGameGuess200Response(
  value: object,
): value is CreateDailyChallengeGameGuess200Response {
  if (!('roundNumber' in value) || value['roundNumber'] === undefined) return false
  if (!('imageId' in value) || value['imageId'] === undefined) return false
  if (!('startedAt' in value) || value['startedAt'] === undefined) return false
  if (!('result' in value) || value['result'] === undefined) return false
  return true
}

export function CreateDailyChallengeGameGuess200ResponseFromJSON(
  json: any,
): CreateDailyChallengeGameGuess200Response {
  return CreateDailyChallengeGameGuess200ResponseFromJSONTyped(json, false)
}

export function CreateDailyChallengeGameGuess200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateDailyChallengeGameGuess200Response {
  if (json == null) {
    return json
  }
  return {
    roundNumber: json['roundNumber'],
    imageId: json['imageId'],
    startedAt: new Date(json['startedAt']),
    result: CreateSinglePlayerGameGuess200ResponseResultFromJSON(json['result']),
  }
}

export function CreateDailyChallengeGameGuess200ResponseToJSON(
  json: any,
): CreateDailyChallengeGameGuess200Response {
  return CreateDailyChallengeGameGuess200ResponseToJSONTyped(json, false)
}

export function CreateDailyChallengeGameGuess200ResponseToJSONTyped(
  value?: CreateDailyChallengeGameGuess200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    roundNumber: value['roundNumber'],
    imageId: value['imageId'],
    startedAt: value['startedAt'].toISOString(),
    result: CreateSinglePlayerGameGuess200ResponseResultToJSON(value['result']),
  }
}
