/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateSinglePlayerGame201ResponseRoundsInnerResultGuess
 */
export interface CreateSinglePlayerGame201ResponseRoundsInnerResultGuess {
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGame201ResponseRoundsInnerResultGuess
   */
  latitude: number
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGame201ResponseRoundsInnerResultGuess
   */
  longitude: number
}

/**
 * Check if a given object implements the CreateSinglePlayerGame201ResponseRoundsInnerResultGuess interface.
 */
export function instanceOfCreateSinglePlayerGame201ResponseRoundsInnerResultGuess(
  value: object,
): value is CreateSinglePlayerGame201ResponseRoundsInnerResultGuess {
  if (!('latitude' in value) || value['latitude'] === undefined) return false
  if (!('longitude' in value) || value['longitude'] === undefined) return false
  return true
}

export function CreateSinglePlayerGame201ResponseRoundsInnerResultGuessFromJSON(
  json: any,
): CreateSinglePlayerGame201ResponseRoundsInnerResultGuess {
  return CreateSinglePlayerGame201ResponseRoundsInnerResultGuessFromJSONTyped(json, false)
}

export function CreateSinglePlayerGame201ResponseRoundsInnerResultGuessFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSinglePlayerGame201ResponseRoundsInnerResultGuess {
  if (json == null) {
    return json
  }
  return {
    latitude: json['latitude'],
    longitude: json['longitude'],
  }
}

export function CreateSinglePlayerGame201ResponseRoundsInnerResultGuessToJSON(
  json: any,
): CreateSinglePlayerGame201ResponseRoundsInnerResultGuess {
  return CreateSinglePlayerGame201ResponseRoundsInnerResultGuessToJSONTyped(json, false)
}

export function CreateSinglePlayerGame201ResponseRoundsInnerResultGuessToJSONTyped(
  value?: CreateSinglePlayerGame201ResponseRoundsInnerResultGuess | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    latitude: value['latitude'],
    longitude: value['longitude'],
  }
}
