/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateUserRequest
 */
export interface CreateUserRequest {
  /**
   *
   * @type {string}
   * @memberof CreateUserRequest
   */
  displayName: string
  /**
   *
   * @type {string}
   * @memberof CreateUserRequest
   */
  country?: string
}

/**
 * Check if a given object implements the CreateUserRequest interface.
 */
export function instanceOfCreateUserRequest(value: object): value is CreateUserRequest {
  if (!('displayName' in value) || value['displayName'] === undefined) return false
  return true
}

export function CreateUserRequestFromJSON(json: any): CreateUserRequest {
  return CreateUserRequestFromJSONTyped(json, false)
}

export function CreateUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateUserRequest {
  if (json == null) {
    return json
  }
  return {
    displayName: json['displayName'],
    country: json['country'] == null ? undefined : json['country'],
  }
}

export function CreateUserRequestToJSON(json: any): CreateUserRequest {
  return CreateUserRequestToJSONTyped(json, false)
}

export function CreateUserRequestToJSONTyped(
  value?: CreateUserRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    displayName: value['displayName'],
    country: value['country'],
  }
}
