/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CreateSinglePlayerGameGuess200ResponseResultTarget } from './CreateSinglePlayerGameGuess200ResponseResultTarget'
import {
  CreateSinglePlayerGameGuess200ResponseResultTargetFromJSON,
  CreateSinglePlayerGameGuess200ResponseResultTargetFromJSONTyped,
  CreateSinglePlayerGameGuess200ResponseResultTargetToJSON,
  CreateSinglePlayerGameGuess200ResponseResultTargetToJSONTyped,
} from './CreateSinglePlayerGameGuess200ResponseResultTarget'
import type { CreateSinglePlayerGameGuessRequestGuess } from './CreateSinglePlayerGameGuessRequestGuess'
import {
  CreateSinglePlayerGameGuessRequestGuessFromJSON,
  CreateSinglePlayerGameGuessRequestGuessFromJSONTyped,
  CreateSinglePlayerGameGuessRequestGuessToJSON,
  CreateSinglePlayerGameGuessRequestGuessToJSONTyped,
} from './CreateSinglePlayerGameGuessRequestGuess'

/**
 *
 * @export
 * @interface CreateSinglePlayerGameGuess200ResponseResult
 */
export interface CreateSinglePlayerGameGuess200ResponseResult {
  /**
   *
   * @type {CreateSinglePlayerGameGuessRequestGuess}
   * @memberof CreateSinglePlayerGameGuess200ResponseResult
   */
  guess: CreateSinglePlayerGameGuessRequestGuess | null
  /**
   *
   * @type {CreateSinglePlayerGameGuess200ResponseResultTarget}
   * @memberof CreateSinglePlayerGameGuess200ResponseResult
   */
  target: CreateSinglePlayerGameGuess200ResponseResultTarget
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGameGuess200ResponseResult
   */
  distanceKm: number | null
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGameGuess200ResponseResult
   */
  score: number
  /**
   *
   * @type {Date}
   * @memberof CreateSinglePlayerGameGuess200ResponseResult
   */
  completedAt: Date
}

/**
 * Check if a given object implements the CreateSinglePlayerGameGuess200ResponseResult interface.
 */
export function instanceOfCreateSinglePlayerGameGuess200ResponseResult(
  value: object,
): value is CreateSinglePlayerGameGuess200ResponseResult {
  if (!('guess' in value) || value['guess'] === undefined) return false
  if (!('target' in value) || value['target'] === undefined) return false
  if (!('distanceKm' in value) || value['distanceKm'] === undefined) return false
  if (!('score' in value) || value['score'] === undefined) return false
  if (!('completedAt' in value) || value['completedAt'] === undefined) return false
  return true
}

export function CreateSinglePlayerGameGuess200ResponseResultFromJSON(
  json: any,
): CreateSinglePlayerGameGuess200ResponseResult {
  return CreateSinglePlayerGameGuess200ResponseResultFromJSONTyped(json, false)
}

export function CreateSinglePlayerGameGuess200ResponseResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSinglePlayerGameGuess200ResponseResult {
  if (json == null) {
    return json
  }
  return {
    guess: CreateSinglePlayerGameGuessRequestGuessFromJSON(json['guess']),
    target: CreateSinglePlayerGameGuess200ResponseResultTargetFromJSON(json['target']),
    distanceKm: json['distanceKm'],
    score: json['score'],
    completedAt: new Date(json['completedAt']),
  }
}

export function CreateSinglePlayerGameGuess200ResponseResultToJSON(
  json: any,
): CreateSinglePlayerGameGuess200ResponseResult {
  return CreateSinglePlayerGameGuess200ResponseResultToJSONTyped(json, false)
}

export function CreateSinglePlayerGameGuess200ResponseResultToJSONTyped(
  value?: CreateSinglePlayerGameGuess200ResponseResult | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    guess: CreateSinglePlayerGameGuessRequestGuessToJSON(value['guess']),
    target: CreateSinglePlayerGameGuess200ResponseResultTargetToJSON(value['target']),
    distanceKm: value['distanceKm'],
    score: value['score'],
    completedAt: value['completedAt'].toISOString(),
  }
}
