/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateWithFriendsGame201Response
 */
export interface CreateWithFriendsGame201Response {
  /**
   *
   * @type {string}
   * @memberof CreateWithFriendsGame201Response
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof CreateWithFriendsGame201Response
   */
  roomKey: string
}

/**
 * Check if a given object implements the CreateWithFriendsGame201Response interface.
 */
export function instanceOfCreateWithFriendsGame201Response(
  value: object,
): value is CreateWithFriendsGame201Response {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('roomKey' in value) || value['roomKey'] === undefined) return false
  return true
}

export function CreateWithFriendsGame201ResponseFromJSON(
  json: any,
): CreateWithFriendsGame201Response {
  return CreateWithFriendsGame201ResponseFromJSONTyped(json, false)
}

export function CreateWithFriendsGame201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateWithFriendsGame201Response {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    roomKey: json['roomKey'],
  }
}

export function CreateWithFriendsGame201ResponseToJSON(
  json: any,
): CreateWithFriendsGame201Response {
  return CreateWithFriendsGame201ResponseToJSONTyped(json, false)
}

export function CreateWithFriendsGame201ResponseToJSONTyped(
  value?: CreateWithFriendsGame201Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    roomKey: value['roomKey'],
  }
}
