/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetTodayDailyChallenge200ResponseGameRoundsInnerResult } from './GetTodayDailyChallenge200ResponseGameRoundsInnerResult'
import {
  GetTodayDailyChallenge200ResponseGameRoundsInnerResultFromJSON,
  GetTodayDailyChallenge200ResponseGameRoundsInnerResultFromJSONTyped,
  GetTodayDailyChallenge200ResponseGameRoundsInnerResultToJSON,
  GetTodayDailyChallenge200ResponseGameRoundsInnerResultToJSONTyped,
} from './GetTodayDailyChallenge200ResponseGameRoundsInnerResult'

/**
 *
 * @export
 * @interface CreateSinglePlayerGameGuessResponse
 */
export interface CreateSinglePlayerGameGuessResponse {
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGameGuessResponse
   */
  roundNumber: number
  /**
   *
   * @type {string}
   * @memberof CreateSinglePlayerGameGuessResponse
   */
  imageId: string
  /**
   *
   * @type {Date}
   * @memberof CreateSinglePlayerGameGuessResponse
   */
  startedAt: Date
  /**
   *
   * @type {GetTodayDailyChallenge200ResponseGameRoundsInnerResult}
   * @memberof CreateSinglePlayerGameGuessResponse
   */
  result: GetTodayDailyChallenge200ResponseGameRoundsInnerResult
}

/**
 * Check if a given object implements the CreateSinglePlayerGameGuessResponse interface.
 */
export function instanceOfCreateSinglePlayerGameGuessResponse(
  value: object,
): value is CreateSinglePlayerGameGuessResponse {
  if (!('roundNumber' in value) || value['roundNumber'] === undefined) return false
  if (!('imageId' in value) || value['imageId'] === undefined) return false
  if (!('startedAt' in value) || value['startedAt'] === undefined) return false
  if (!('result' in value) || value['result'] === undefined) return false
  return true
}

export function CreateSinglePlayerGameGuessResponseFromJSON(
  json: any,
): CreateSinglePlayerGameGuessResponse {
  return CreateSinglePlayerGameGuessResponseFromJSONTyped(json, false)
}

export function CreateSinglePlayerGameGuessResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSinglePlayerGameGuessResponse {
  if (json == null) {
    return json
  }
  return {
    roundNumber: json['roundNumber'],
    imageId: json['imageId'],
    startedAt: new Date(json['startedAt']),
    result: GetTodayDailyChallenge200ResponseGameRoundsInnerResultFromJSON(json['result']),
  }
}

export function CreateSinglePlayerGameGuessResponseToJSON(
  json: any,
): CreateSinglePlayerGameGuessResponse {
  return CreateSinglePlayerGameGuessResponseToJSONTyped(json, false)
}

export function CreateSinglePlayerGameGuessResponseToJSONTyped(
  value?: CreateSinglePlayerGameGuessResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    roundNumber: value['roundNumber'],
    imageId: value['imageId'],
    startedAt: value['startedAt'].toISOString(),
    result: GetTodayDailyChallenge200ResponseGameRoundsInnerResultToJSON(value['result']),
  }
}
