/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateSinglePlayerGameGuessRequestGuess
 */
export interface CreateSinglePlayerGameGuessRequestGuess {
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGameGuessRequestGuess
   */
  latitude: number
  /**
   *
   * @type {number}
   * @memberof CreateSinglePlayerGameGuessRequestGuess
   */
  longitude: number
}

/**
 * Check if a given object implements the CreateSinglePlayerGameGuessRequestGuess interface.
 */
export function instanceOfCreateSinglePlayerGameGuessRequestGuess(
  value: object,
): value is CreateSinglePlayerGameGuessRequestGuess {
  if (!('latitude' in value) || value['latitude'] === undefined) return false
  if (!('longitude' in value) || value['longitude'] === undefined) return false
  return true
}

export function CreateSinglePlayerGameGuessRequestGuessFromJSON(
  json: any,
): CreateSinglePlayerGameGuessRequestGuess {
  return CreateSinglePlayerGameGuessRequestGuessFromJSONTyped(json, false)
}

export function CreateSinglePlayerGameGuessRequestGuessFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateSinglePlayerGameGuessRequestGuess {
  if (json == null) {
    return json
  }
  return {
    latitude: json['latitude'],
    longitude: json['longitude'],
  }
}

export function CreateSinglePlayerGameGuessRequestGuessToJSON(
  json: any,
): CreateSinglePlayerGameGuessRequestGuess {
  return CreateSinglePlayerGameGuessRequestGuessToJSONTyped(json, false)
}

export function CreateSinglePlayerGameGuessRequestGuessToJSONTyped(
  value?: CreateSinglePlayerGameGuessRequestGuess | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    latitude: value['latitude'],
    longitude: value['longitude'],
  }
}
