/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { CreateWithFriendsGameGuessRequestGuess } from './CreateWithFriendsGameGuessRequestGuess'
import {
  CreateWithFriendsGameGuessRequestGuessFromJSON,
  CreateWithFriendsGameGuessRequestGuessFromJSONTyped,
  CreateWithFriendsGameGuessRequestGuessToJSON,
  CreateWithFriendsGameGuessRequestGuessToJSONTyped,
} from './CreateWithFriendsGameGuessRequestGuess'

/**
 *
 * @export
 * @interface CreateWithFriendsGameGuessRequest
 */
export interface CreateWithFriendsGameGuessRequest {
  /**
   *
   * @type {CreateWithFriendsGameGuessRequestGuess}
   * @memberof CreateWithFriendsGameGuessRequest
   */
  guess: CreateWithFriendsGameGuessRequestGuess
}

/**
 * Check if a given object implements the CreateWithFriendsGameGuessRequest interface.
 */
export function instanceOfCreateWithFriendsGameGuessRequest(
  value: object,
): value is CreateWithFriendsGameGuessRequest {
  if (!('guess' in value) || value['guess'] === undefined) return false
  return true
}

export function CreateWithFriendsGameGuessRequestFromJSON(
  json: any,
): CreateWithFriendsGameGuessRequest {
  return CreateWithFriendsGameGuessRequestFromJSONTyped(json, false)
}

export function CreateWithFriendsGameGuessRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateWithFriendsGameGuessRequest {
  if (json == null) {
    return json
  }
  return {
    guess: CreateWithFriendsGameGuessRequestGuessFromJSON(json['guess']),
  }
}

export function CreateWithFriendsGameGuessRequestToJSON(
  json: any,
): CreateWithFriendsGameGuessRequest {
  return CreateWithFriendsGameGuessRequestToJSONTyped(json, false)
}

export function CreateWithFriendsGameGuessRequestToJSONTyped(
  value?: CreateWithFriendsGameGuessRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    guess: CreateWithFriendsGameGuessRequestGuessToJSON(value['guess']),
  }
}
