/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetCurrentUserResponse
 */
export interface GetCurrentUserResponse {
  /**
   *
   * @type {string}
   * @memberof GetCurrentUserResponse
   */
  userId: string
  /**
   *
   * @type {string}
   * @memberof GetCurrentUserResponse
   */
  displayName: string
  /**
   *
   * @type {string}
   * @memberof GetCurrentUserResponse
   */
  country: string | null
  /**
   *
   * @type {number}
   * @memberof GetCurrentUserResponse
   */
  gamesPlayed: number
  /**
   *
   * @type {number}
   * @memberof GetCurrentUserResponse
   */
  bestScore: number
  /**
   *
   * @type {number}
   * @memberof GetCurrentUserResponse
   */
  averageScore: number
  /**
   *
   * @type {string}
   * @memberof GetCurrentUserResponse
   */
  distanceUnit: GetCurrentUserResponseDistanceUnitEnum
  /**
   *
   * @type {string}
   * @memberof GetCurrentUserResponse
   */
  dailyChallengeStatus: GetCurrentUserResponseDailyChallengeStatusEnum
  /**
   *
   * @type {Date}
   * @memberof GetCurrentUserResponse
   */
  createdAt: Date
  /**
   *
   * @type {Date}
   * @memberof GetCurrentUserResponse
   */
  updatedAt: Date
}

/**
 * @export
 */
export const GetCurrentUserResponseDistanceUnitEnum = {
  Km: 'km',
  Mile: 'mile',
} as const
export type GetCurrentUserResponseDistanceUnitEnum =
  (typeof GetCurrentUserResponseDistanceUnitEnum)[keyof typeof GetCurrentUserResponseDistanceUnitEnum]

/**
 * @export
 */
export const GetCurrentUserResponseDailyChallengeStatusEnum = {
  Available: 'available',
  Ongoing: 'ongoing',
  Completed: 'completed',
  Unavailable: 'unavailable',
} as const
export type GetCurrentUserResponseDailyChallengeStatusEnum =
  (typeof GetCurrentUserResponseDailyChallengeStatusEnum)[keyof typeof GetCurrentUserResponseDailyChallengeStatusEnum]

/**
 * Check if a given object implements the GetCurrentUserResponse interface.
 */
export function instanceOfGetCurrentUserResponse(value: object): value is GetCurrentUserResponse {
  if (!('userId' in value) || value['userId'] === undefined) return false
  if (!('displayName' in value) || value['displayName'] === undefined) return false
  if (!('country' in value) || value['country'] === undefined) return false
  if (!('gamesPlayed' in value) || value['gamesPlayed'] === undefined) return false
  if (!('bestScore' in value) || value['bestScore'] === undefined) return false
  if (!('averageScore' in value) || value['averageScore'] === undefined) return false
  if (!('distanceUnit' in value) || value['distanceUnit'] === undefined) return false
  if (!('dailyChallengeStatus' in value) || value['dailyChallengeStatus'] === undefined)
    return false
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false
  return true
}

export function GetCurrentUserResponseFromJSON(json: any): GetCurrentUserResponse {
  return GetCurrentUserResponseFromJSONTyped(json, false)
}

export function GetCurrentUserResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetCurrentUserResponse {
  if (json == null) {
    return json
  }
  return {
    userId: json['userId'],
    displayName: json['displayName'],
    country: json['country'],
    gamesPlayed: json['gamesPlayed'],
    bestScore: json['bestScore'],
    averageScore: json['averageScore'],
    distanceUnit: json['distanceUnit'],
    dailyChallengeStatus: json['dailyChallengeStatus'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
  }
}

export function GetCurrentUserResponseToJSON(json: any): GetCurrentUserResponse {
  return GetCurrentUserResponseToJSONTyped(json, false)
}

export function GetCurrentUserResponseToJSONTyped(
  value?: GetCurrentUserResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    userId: value['userId'],
    displayName: value['displayName'],
    country: value['country'],
    gamesPlayed: value['gamesPlayed'],
    bestScore: value['bestScore'],
    averageScore: value['averageScore'],
    distanceUnit: value['distanceUnit'],
    dailyChallengeStatus: value['dailyChallengeStatus'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
  }
}
