/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetCurrentUser200Response
 */
export interface GetCurrentUser200Response {
  /**
   *
   * @type {string}
   * @memberof GetCurrentUser200Response
   */
  userId: string
  /**
   *
   * @type {string}
   * @memberof GetCurrentUser200Response
   */
  displayName: string
  /**
   *
   * @type {string}
   * @memberof GetCurrentUser200Response
   */
  country: string | null
  /**
   *
   * @type {number}
   * @memberof GetCurrentUser200Response
   */
  gamesPlayed: number
  /**
   *
   * @type {number}
   * @memberof GetCurrentUser200Response
   */
  bestScore: number
  /**
   *
   * @type {number}
   * @memberof GetCurrentUser200Response
   */
  averageScore: number
  /**
   *
   * @type {string}
   * @memberof GetCurrentUser200Response
   */
  distanceUnit: GetCurrentUser200ResponseDistanceUnitEnum
  /**
   *
   * @type {string}
   * @memberof GetCurrentUser200Response
   */
  dailyChallengeStatus: GetCurrentUser200ResponseDailyChallengeStatusEnum
  /**
   *
   * @type {Date}
   * @memberof GetCurrentUser200Response
   */
  createdAt: Date
  /**
   *
   * @type {Date}
   * @memberof GetCurrentUser200Response
   */
  updatedAt: Date
}

/**
 * @export
 */
export const GetCurrentUser200ResponseDistanceUnitEnum = {
  Km: 'km',
  Mile: 'mile',
} as const
export type GetCurrentUser200ResponseDistanceUnitEnum =
  (typeof GetCurrentUser200ResponseDistanceUnitEnum)[keyof typeof GetCurrentUser200ResponseDistanceUnitEnum]

/**
 * @export
 */
export const GetCurrentUser200ResponseDailyChallengeStatusEnum = {
  Available: 'available',
  Ongoing: 'ongoing',
  Completed: 'completed',
  Unavailable: 'unavailable',
} as const
export type GetCurrentUser200ResponseDailyChallengeStatusEnum =
  (typeof GetCurrentUser200ResponseDailyChallengeStatusEnum)[keyof typeof GetCurrentUser200ResponseDailyChallengeStatusEnum]

/**
 * Check if a given object implements the GetCurrentUser200Response interface.
 */
export function instanceOfGetCurrentUser200Response(
  value: object,
): value is GetCurrentUser200Response {
  if (!('userId' in value) || value['userId'] === undefined) return false
  if (!('displayName' in value) || value['displayName'] === undefined) return false
  if (!('country' in value) || value['country'] === undefined) return false
  if (!('gamesPlayed' in value) || value['gamesPlayed'] === undefined) return false
  if (!('bestScore' in value) || value['bestScore'] === undefined) return false
  if (!('averageScore' in value) || value['averageScore'] === undefined) return false
  if (!('distanceUnit' in value) || value['distanceUnit'] === undefined) return false
  if (!('dailyChallengeStatus' in value) || value['dailyChallengeStatus'] === undefined)
    return false
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false
  return true
}

export function GetCurrentUser200ResponseFromJSON(json: any): GetCurrentUser200Response {
  return GetCurrentUser200ResponseFromJSONTyped(json, false)
}

export function GetCurrentUser200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetCurrentUser200Response {
  if (json == null) {
    return json
  }
  return {
    userId: json['userId'],
    displayName: json['displayName'],
    country: json['country'],
    gamesPlayed: json['gamesPlayed'],
    bestScore: json['bestScore'],
    averageScore: json['averageScore'],
    distanceUnit: json['distanceUnit'],
    dailyChallengeStatus: json['dailyChallengeStatus'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
  }
}

export function GetCurrentUser200ResponseToJSON(json: any): GetCurrentUser200Response {
  return GetCurrentUser200ResponseToJSONTyped(json, false)
}

export function GetCurrentUser200ResponseToJSONTyped(
  value?: GetCurrentUser200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    userId: value['userId'],
    displayName: value['displayName'],
    country: value['country'],
    gamesPlayed: value['gamesPlayed'],
    bestScore: value['bestScore'],
    averageScore: value['averageScore'],
    distanceUnit: value['distanceUnit'],
    dailyChallengeStatus: value['dailyChallengeStatus'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
  }
}
