/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetCurrentUser404Response
 */
export interface GetCurrentUser404Response {
  /**
   *
   * @type {string}
   * @memberof GetCurrentUser404Response
   */
  code: string
  /**
   *
   * @type {string}
   * @memberof GetCurrentUser404Response
   */
  message: string
}

/**
 * Check if a given object implements the GetCurrentUser404Response interface.
 */
export function instanceOfGetCurrentUser404Response(
  value: object,
): value is GetCurrentUser404Response {
  if (!('code' in value) || value['code'] === undefined) return false
  if (!('message' in value) || value['message'] === undefined) return false
  return true
}

export function GetCurrentUser404ResponseFromJSON(json: any): GetCurrentUser404Response {
  return GetCurrentUser404ResponseFromJSONTyped(json, false)
}

export function GetCurrentUser404ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetCurrentUser404Response {
  if (json == null) {
    return json
  }
  return {
    code: json['code'],
    message: json['message'],
  }
}

export function GetCurrentUser404ResponseToJSON(json: any): GetCurrentUser404Response {
  return GetCurrentUser404ResponseToJSONTyped(json, false)
}

export function GetCurrentUser404ResponseToJSONTyped(
  value?: GetCurrentUser404Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value['code'],
    message: value['message'],
  }
}
