/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetDailyChallengeLeaderboard200ResponseInner
 */
export interface GetDailyChallengeLeaderboard200ResponseInner {
  /**
   *
   * @type {number}
   * @memberof GetDailyChallengeLeaderboard200ResponseInner
   */
  rank: number
  /**
   *
   * @type {string}
   * @memberof GetDailyChallengeLeaderboard200ResponseInner
   */
  userId: string
  /**
   *
   * @type {string}
   * @memberof GetDailyChallengeLeaderboard200ResponseInner
   */
  displayName: string
  /**
   *
   * @type {string}
   * @memberof GetDailyChallengeLeaderboard200ResponseInner
   */
  country: string | null
  /**
   *
   * @type {number}
   * @memberof GetDailyChallengeLeaderboard200ResponseInner
   */
  totalScore: number
}

/**
 * Check if a given object implements the GetDailyChallengeLeaderboard200ResponseInner interface.
 */
export function instanceOfGetDailyChallengeLeaderboard200ResponseInner(
  value: object,
): value is GetDailyChallengeLeaderboard200ResponseInner {
  if (!('rank' in value) || value['rank'] === undefined) return false
  if (!('userId' in value) || value['userId'] === undefined) return false
  if (!('displayName' in value) || value['displayName'] === undefined) return false
  if (!('country' in value) || value['country'] === undefined) return false
  if (!('totalScore' in value) || value['totalScore'] === undefined) return false
  return true
}

export function GetDailyChallengeLeaderboard200ResponseInnerFromJSON(
  json: any,
): GetDailyChallengeLeaderboard200ResponseInner {
  return GetDailyChallengeLeaderboard200ResponseInnerFromJSONTyped(json, false)
}

export function GetDailyChallengeLeaderboard200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetDailyChallengeLeaderboard200ResponseInner {
  if (json == null) {
    return json
  }
  return {
    rank: json['rank'],
    userId: json['userId'],
    displayName: json['displayName'],
    country: json['country'],
    totalScore: json['totalScore'],
  }
}

export function GetDailyChallengeLeaderboard200ResponseInnerToJSON(
  json: any,
): GetDailyChallengeLeaderboard200ResponseInner {
  return GetDailyChallengeLeaderboard200ResponseInnerToJSONTyped(json, false)
}

export function GetDailyChallengeLeaderboard200ResponseInnerToJSONTyped(
  value?: GetDailyChallengeLeaderboard200ResponseInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    rank: value['rank'],
    userId: value['userId'],
    displayName: value['displayName'],
    country: value['country'],
    totalScore: value['totalScore'],
  }
}
