/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetDailyChallengeGames200ResponseInner
 */
export interface GetDailyChallengeGames200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof GetDailyChallengeGames200ResponseInner
   */
  id: string
  /**
   *
   * @type {Date}
   * @memberof GetDailyChallengeGames200ResponseInner
   */
  date: Date
  /**
   *
   * @type {number}
   * @memberof GetDailyChallengeGames200ResponseInner
   */
  totalScore: number
  /**
   *
   * @type {number}
   * @memberof GetDailyChallengeGames200ResponseInner
   */
  totalDistanceKm: number | null
  /**
   *
   * @type {Date}
   * @memberof GetDailyChallengeGames200ResponseInner
   */
  completedAt: Date
}

/**
 * Check if a given object implements the GetDailyChallengeGames200ResponseInner interface.
 */
export function instanceOfGetDailyChallengeGames200ResponseInner(
  value: object,
): value is GetDailyChallengeGames200ResponseInner {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('date' in value) || value['date'] === undefined) return false
  if (!('totalScore' in value) || value['totalScore'] === undefined) return false
  if (!('totalDistanceKm' in value) || value['totalDistanceKm'] === undefined) return false
  if (!('completedAt' in value) || value['completedAt'] === undefined) return false
  return true
}

export function GetDailyChallengeGames200ResponseInnerFromJSON(
  json: any,
): GetDailyChallengeGames200ResponseInner {
  return GetDailyChallengeGames200ResponseInnerFromJSONTyped(json, false)
}

export function GetDailyChallengeGames200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetDailyChallengeGames200ResponseInner {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    date: new Date(json['date']),
    totalScore: json['totalScore'],
    totalDistanceKm: json['totalDistanceKm'],
    completedAt: new Date(json['completedAt']),
  }
}

export function GetDailyChallengeGames200ResponseInnerToJSON(
  json: any,
): GetDailyChallengeGames200ResponseInner {
  return GetDailyChallengeGames200ResponseInnerToJSONTyped(json, false)
}

export function GetDailyChallengeGames200ResponseInnerToJSONTyped(
  value?: GetDailyChallengeGames200ResponseInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    date: value['date'].toISOString().substring(0, 10),
    totalScore: value['totalScore'],
    totalDistanceKm: value['totalDistanceKm'],
    completedAt: value['completedAt'].toISOString(),
  }
}
