/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetHealthResponse
 */
export interface GetHealthResponse {
  /**
   * Health status message.
   * @type {string}
   * @memberof GetHealthResponse
   */
  message: string
}

/**
 * Check if a given object implements the GetHealthResponse interface.
 */
export function instanceOfGetHealthResponse(value: object): value is GetHealthResponse {
  if (!('message' in value) || value['message'] === undefined) return false
  return true
}

export function GetHealthResponseFromJSON(json: any): GetHealthResponse {
  return GetHealthResponseFromJSONTyped(json, false)
}

export function GetHealthResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetHealthResponse {
  if (json == null) {
    return json
  }
  return {
    message: json['message'],
  }
}

export function GetHealthResponseToJSON(json: any): GetHealthResponse {
  return GetHealthResponseToJSONTyped(json, false)
}

export function GetHealthResponseToJSONTyped(
  value?: GetHealthResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    message: value['message'],
  }
}
