/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetHealth200Response
 */
export interface GetHealth200Response {
  /**
   * Health status message.
   * @type {string}
   * @memberof GetHealth200Response
   */
  message: string
}

/**
 * Check if a given object implements the GetHealth200Response interface.
 */
export function instanceOfGetHealth200Response(value: object): value is GetHealth200Response {
  if (!('message' in value) || value['message'] === undefined) return false
  return true
}

export function GetHealth200ResponseFromJSON(json: any): GetHealth200Response {
  return GetHealth200ResponseFromJSONTyped(json, false)
}

export function GetHealth200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetHealth200Response {
  if (json == null) {
    return json
  }
  return {
    message: json['message'],
  }
}

export function GetHealth200ResponseToJSON(json: any): GetHealth200Response {
  return GetHealth200ResponseToJSONTyped(json, false)
}

export function GetHealth200ResponseToJSONTyped(
  value?: GetHealth200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    message: value['message'],
  }
}
