/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetSinglePlayerGameResponseRoundsInner } from './GetSinglePlayerGameResponseRoundsInner'
import {
  GetSinglePlayerGameResponseRoundsInnerFromJSON,
  GetSinglePlayerGameResponseRoundsInnerFromJSONTyped,
  GetSinglePlayerGameResponseRoundsInnerToJSON,
  GetSinglePlayerGameResponseRoundsInnerToJSONTyped,
} from './GetSinglePlayerGameResponseRoundsInner'

/**
 *
 * @export
 * @interface GetSinglePlayerGameResponse
 */
export interface GetSinglePlayerGameResponse {
  /**
   *
   * @type {string}
   * @memberof GetSinglePlayerGameResponse
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof GetSinglePlayerGameResponse
   */
  status: GetSinglePlayerGameResponseStatusEnum
  /**
   *
   * @type {number}
   * @memberof GetSinglePlayerGameResponse
   */
  currentRound: number
  /**
   *
   * @type {Array<GetSinglePlayerGameResponseRoundsInner>}
   * @memberof GetSinglePlayerGameResponse
   */
  rounds: Array<GetSinglePlayerGameResponseRoundsInner>
  /**
   *
   * @type {Date}
   * @memberof GetSinglePlayerGameResponse
   */
  createdAt: Date
  /**
   *
   * @type {Date}
   * @memberof GetSinglePlayerGameResponse
   */
  completedAt?: Date
}

/**
 * @export
 */
export const GetSinglePlayerGameResponseStatusEnum = {
  Ongoing: 'ongoing',
  Completed: 'completed',
} as const
export type GetSinglePlayerGameResponseStatusEnum =
  (typeof GetSinglePlayerGameResponseStatusEnum)[keyof typeof GetSinglePlayerGameResponseStatusEnum]

/**
 * Check if a given object implements the GetSinglePlayerGameResponse interface.
 */
export function instanceOfGetSinglePlayerGameResponse(
  value: object,
): value is GetSinglePlayerGameResponse {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('status' in value) || value['status'] === undefined) return false
  if (!('currentRound' in value) || value['currentRound'] === undefined) return false
  if (!('rounds' in value) || value['rounds'] === undefined) return false
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false
  return true
}

export function GetSinglePlayerGameResponseFromJSON(json: any): GetSinglePlayerGameResponse {
  return GetSinglePlayerGameResponseFromJSONTyped(json, false)
}

export function GetSinglePlayerGameResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetSinglePlayerGameResponse {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    status: json['status'],
    currentRound: json['currentRound'],
    rounds: (json['rounds'] as Array<any>).map(GetSinglePlayerGameResponseRoundsInnerFromJSON),
    createdAt: new Date(json['createdAt']),
    completedAt: json['completedAt'] == null ? undefined : new Date(json['completedAt']),
  }
}

export function GetSinglePlayerGameResponseToJSON(json: any): GetSinglePlayerGameResponse {
  return GetSinglePlayerGameResponseToJSONTyped(json, false)
}

export function GetSinglePlayerGameResponseToJSONTyped(
  value?: GetSinglePlayerGameResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    status: value['status'],
    currentRound: value['currentRound'],
    rounds: (value['rounds'] as Array<any>).map(GetSinglePlayerGameResponseRoundsInnerToJSON),
    createdAt: value['createdAt'].toISOString(),
    completedAt:
      value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
  }
}
