/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetSinglePlayerGames200ResponseInner
 */
export interface GetSinglePlayerGames200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof GetSinglePlayerGames200ResponseInner
   */
  id: string
  /**
   *
   * @type {number}
   * @memberof GetSinglePlayerGames200ResponseInner
   */
  totalScore: number
  /**
   *
   * @type {number}
   * @memberof GetSinglePlayerGames200ResponseInner
   */
  totalDistanceKm: number | null
  /**
   *
   * @type {Date}
   * @memberof GetSinglePlayerGames200ResponseInner
   */
  createdAt: Date
  /**
   *
   * @type {Date}
   * @memberof GetSinglePlayerGames200ResponseInner
   */
  completedAt: Date
}

/**
 * Check if a given object implements the GetSinglePlayerGames200ResponseInner interface.
 */
export function instanceOfGetSinglePlayerGames200ResponseInner(
  value: object,
): value is GetSinglePlayerGames200ResponseInner {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('totalScore' in value) || value['totalScore'] === undefined) return false
  if (!('totalDistanceKm' in value) || value['totalDistanceKm'] === undefined) return false
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false
  if (!('completedAt' in value) || value['completedAt'] === undefined) return false
  return true
}

export function GetSinglePlayerGames200ResponseInnerFromJSON(
  json: any,
): GetSinglePlayerGames200ResponseInner {
  return GetSinglePlayerGames200ResponseInnerFromJSONTyped(json, false)
}

export function GetSinglePlayerGames200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetSinglePlayerGames200ResponseInner {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    totalScore: json['totalScore'],
    totalDistanceKm: json['totalDistanceKm'],
    createdAt: new Date(json['createdAt']),
    completedAt: new Date(json['completedAt']),
  }
}

export function GetSinglePlayerGames200ResponseInnerToJSON(
  json: any,
): GetSinglePlayerGames200ResponseInner {
  return GetSinglePlayerGames200ResponseInnerToJSONTyped(json, false)
}

export function GetSinglePlayerGames200ResponseInnerToJSONTyped(
  value?: GetSinglePlayerGames200ResponseInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    totalScore: value['totalScore'],
    totalDistanceKm: value['totalDistanceKm'],
    createdAt: value['createdAt'].toISOString(),
    completedAt: value['completedAt'].toISOString(),
  }
}
