/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetSinglePlayerGameResponseRoundsInnerResultGuess
 */
export interface GetSinglePlayerGameResponseRoundsInnerResultGuess {
  /**
   *
   * @type {number}
   * @memberof GetSinglePlayerGameResponseRoundsInnerResultGuess
   */
  latitude: number
  /**
   *
   * @type {number}
   * @memberof GetSinglePlayerGameResponseRoundsInnerResultGuess
   */
  longitude: number
}

/**
 * Check if a given object implements the GetSinglePlayerGameResponseRoundsInnerResultGuess interface.
 */
export function instanceOfGetSinglePlayerGameResponseRoundsInnerResultGuess(
  value: object,
): value is GetSinglePlayerGameResponseRoundsInnerResultGuess {
  if (!('latitude' in value) || value['latitude'] === undefined) return false
  if (!('longitude' in value) || value['longitude'] === undefined) return false
  return true
}

export function GetSinglePlayerGameResponseRoundsInnerResultGuessFromJSON(
  json: any,
): GetSinglePlayerGameResponseRoundsInnerResultGuess {
  return GetSinglePlayerGameResponseRoundsInnerResultGuessFromJSONTyped(json, false)
}

export function GetSinglePlayerGameResponseRoundsInnerResultGuessFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetSinglePlayerGameResponseRoundsInnerResultGuess {
  if (json == null) {
    return json
  }
  return {
    latitude: json['latitude'],
    longitude: json['longitude'],
  }
}

export function GetSinglePlayerGameResponseRoundsInnerResultGuessToJSON(
  json: any,
): GetSinglePlayerGameResponseRoundsInnerResultGuess {
  return GetSinglePlayerGameResponseRoundsInnerResultGuessToJSONTyped(json, false)
}

export function GetSinglePlayerGameResponseRoundsInnerResultGuessToJSONTyped(
  value?: GetSinglePlayerGameResponseRoundsInnerResultGuess | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    latitude: value['latitude'],
    longitude: value['longitude'],
  }
}
