/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetSinglePlayerGameResponseRoundsInnerResultTarget
 */
export interface GetSinglePlayerGameResponseRoundsInnerResultTarget {
  /**
   *
   * @type {number}
   * @memberof GetSinglePlayerGameResponseRoundsInnerResultTarget
   */
  latitude: number
  /**
   *
   * @type {number}
   * @memberof GetSinglePlayerGameResponseRoundsInnerResultTarget
   */
  longitude: number
}

/**
 * Check if a given object implements the GetSinglePlayerGameResponseRoundsInnerResultTarget interface.
 */
export function instanceOfGetSinglePlayerGameResponseRoundsInnerResultTarget(
  value: object,
): value is GetSinglePlayerGameResponseRoundsInnerResultTarget {
  if (!('latitude' in value) || value['latitude'] === undefined) return false
  if (!('longitude' in value) || value['longitude'] === undefined) return false
  return true
}

export function GetSinglePlayerGameResponseRoundsInnerResultTargetFromJSON(
  json: any,
): GetSinglePlayerGameResponseRoundsInnerResultTarget {
  return GetSinglePlayerGameResponseRoundsInnerResultTargetFromJSONTyped(json, false)
}

export function GetSinglePlayerGameResponseRoundsInnerResultTargetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetSinglePlayerGameResponseRoundsInnerResultTarget {
  if (json == null) {
    return json
  }
  return {
    latitude: json['latitude'],
    longitude: json['longitude'],
  }
}

export function GetSinglePlayerGameResponseRoundsInnerResultTargetToJSON(
  json: any,
): GetSinglePlayerGameResponseRoundsInnerResultTarget {
  return GetSinglePlayerGameResponseRoundsInnerResultTargetToJSONTyped(json, false)
}

export function GetSinglePlayerGameResponseRoundsInnerResultTargetToJSONTyped(
  value?: GetSinglePlayerGameResponseRoundsInnerResultTarget | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    latitude: value['latitude'],
    longitude: value['longitude'],
  }
}
