/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetSinglePlayerGames401Response
 */
export interface GetSinglePlayerGames401Response {
  /**
   *
   * @type {string}
   * @memberof GetSinglePlayerGames401Response
   */
  code: string
  /**
   *
   * @type {string}
   * @memberof GetSinglePlayerGames401Response
   */
  message: string
}

/**
 * Check if a given object implements the GetSinglePlayerGames401Response interface.
 */
export function instanceOfGetSinglePlayerGames401Response(
  value: object,
): value is GetSinglePlayerGames401Response {
  if (!('code' in value) || value['code'] === undefined) return false
  if (!('message' in value) || value['message'] === undefined) return false
  return true
}

export function GetSinglePlayerGames401ResponseFromJSON(
  json: any,
): GetSinglePlayerGames401Response {
  return GetSinglePlayerGames401ResponseFromJSONTyped(json, false)
}

export function GetSinglePlayerGames401ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetSinglePlayerGames401Response {
  if (json == null) {
    return json
  }
  return {
    code: json['code'],
    message: json['message'],
  }
}

export function GetSinglePlayerGames401ResponseToJSON(json: any): GetSinglePlayerGames401Response {
  return GetSinglePlayerGames401ResponseToJSONTyped(json, false)
}

export function GetSinglePlayerGames401ResponseToJSONTyped(
  value?: GetSinglePlayerGames401Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    code: value['code'],
    message: value['message'],
  }
}
