/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetSinglePlayerGameResponseRoundsInnerResult } from './GetSinglePlayerGameResponseRoundsInnerResult'
import {
  GetSinglePlayerGameResponseRoundsInnerResultFromJSON,
  GetSinglePlayerGameResponseRoundsInnerResultFromJSONTyped,
  GetSinglePlayerGameResponseRoundsInnerResultToJSON,
  GetSinglePlayerGameResponseRoundsInnerResultToJSONTyped,
} from './GetSinglePlayerGameResponseRoundsInnerResult'

/**
 *
 * @export
 * @interface GetSinglePlayerGameResponseRoundsInner
 */
export interface GetSinglePlayerGameResponseRoundsInner {
  /**
   *
   * @type {number}
   * @memberof GetSinglePlayerGameResponseRoundsInner
   */
  roundNumber: number
  /**
   *
   * @type {string}
   * @memberof GetSinglePlayerGameResponseRoundsInner
   */
  imageId: string
  /**
   *
   * @type {Date}
   * @memberof GetSinglePlayerGameResponseRoundsInner
   */
  startedAt: Date
  /**
   *
   * @type {GetSinglePlayerGameResponseRoundsInnerResult}
   * @memberof GetSinglePlayerGameResponseRoundsInner
   */
  result?: GetSinglePlayerGameResponseRoundsInnerResult
}

/**
 * Check if a given object implements the GetSinglePlayerGameResponseRoundsInner interface.
 */
export function instanceOfGetSinglePlayerGameResponseRoundsInner(
  value: object,
): value is GetSinglePlayerGameResponseRoundsInner {
  if (!('roundNumber' in value) || value['roundNumber'] === undefined) return false
  if (!('imageId' in value) || value['imageId'] === undefined) return false
  if (!('startedAt' in value) || value['startedAt'] === undefined) return false
  return true
}

export function GetSinglePlayerGameResponseRoundsInnerFromJSON(
  json: any,
): GetSinglePlayerGameResponseRoundsInner {
  return GetSinglePlayerGameResponseRoundsInnerFromJSONTyped(json, false)
}

export function GetSinglePlayerGameResponseRoundsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetSinglePlayerGameResponseRoundsInner {
  if (json == null) {
    return json
  }
  return {
    roundNumber: json['roundNumber'],
    imageId: json['imageId'],
    startedAt: new Date(json['startedAt']),
    result:
      json['result'] == null
        ? undefined
        : GetSinglePlayerGameResponseRoundsInnerResultFromJSON(json['result']),
  }
}

export function GetSinglePlayerGameResponseRoundsInnerToJSON(
  json: any,
): GetSinglePlayerGameResponseRoundsInner {
  return GetSinglePlayerGameResponseRoundsInnerToJSONTyped(json, false)
}

export function GetSinglePlayerGameResponseRoundsInnerToJSONTyped(
  value?: GetSinglePlayerGameResponseRoundsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    roundNumber: value['roundNumber'],
    imageId: value['imageId'],
    startedAt: value['startedAt'].toISOString(),
    result: GetSinglePlayerGameResponseRoundsInnerResultToJSON(value['result']),
  }
}
