/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetSinglePlayerGameResponseRoundsInnerResultGuess } from './GetSinglePlayerGameResponseRoundsInnerResultGuess'
import {
  GetSinglePlayerGameResponseRoundsInnerResultGuessFromJSON,
  GetSinglePlayerGameResponseRoundsInnerResultGuessFromJSONTyped,
  GetSinglePlayerGameResponseRoundsInnerResultGuessToJSON,
  GetSinglePlayerGameResponseRoundsInnerResultGuessToJSONTyped,
} from './GetSinglePlayerGameResponseRoundsInnerResultGuess'
import type { GetSinglePlayerGameResponseRoundsInnerResultTarget } from './GetSinglePlayerGameResponseRoundsInnerResultTarget'
import {
  GetSinglePlayerGameResponseRoundsInnerResultTargetFromJSON,
  GetSinglePlayerGameResponseRoundsInnerResultTargetFromJSONTyped,
  GetSinglePlayerGameResponseRoundsInnerResultTargetToJSON,
  GetSinglePlayerGameResponseRoundsInnerResultTargetToJSONTyped,
} from './GetSinglePlayerGameResponseRoundsInnerResultTarget'

/**
 *
 * @export
 * @interface GetSinglePlayerGameResponseRoundsInnerResult
 */
export interface GetSinglePlayerGameResponseRoundsInnerResult {
  /**
   *
   * @type {GetSinglePlayerGameResponseRoundsInnerResultGuess}
   * @memberof GetSinglePlayerGameResponseRoundsInnerResult
   */
  guess: GetSinglePlayerGameResponseRoundsInnerResultGuess | null
  /**
   *
   * @type {GetSinglePlayerGameResponseRoundsInnerResultTarget}
   * @memberof GetSinglePlayerGameResponseRoundsInnerResult
   */
  target: GetSinglePlayerGameResponseRoundsInnerResultTarget
  /**
   *
   * @type {number}
   * @memberof GetSinglePlayerGameResponseRoundsInnerResult
   */
  distanceKm: number | null
  /**
   *
   * @type {number}
   * @memberof GetSinglePlayerGameResponseRoundsInnerResult
   */
  score: number
  /**
   *
   * @type {Date}
   * @memberof GetSinglePlayerGameResponseRoundsInnerResult
   */
  completedAt: Date
}

/**
 * Check if a given object implements the GetSinglePlayerGameResponseRoundsInnerResult interface.
 */
export function instanceOfGetSinglePlayerGameResponseRoundsInnerResult(
  value: object,
): value is GetSinglePlayerGameResponseRoundsInnerResult {
  if (!('guess' in value) || value['guess'] === undefined) return false
  if (!('target' in value) || value['target'] === undefined) return false
  if (!('distanceKm' in value) || value['distanceKm'] === undefined) return false
  if (!('score' in value) || value['score'] === undefined) return false
  if (!('completedAt' in value) || value['completedAt'] === undefined) return false
  return true
}

export function GetSinglePlayerGameResponseRoundsInnerResultFromJSON(
  json: any,
): GetSinglePlayerGameResponseRoundsInnerResult {
  return GetSinglePlayerGameResponseRoundsInnerResultFromJSONTyped(json, false)
}

export function GetSinglePlayerGameResponseRoundsInnerResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetSinglePlayerGameResponseRoundsInnerResult {
  if (json == null) {
    return json
  }
  return {
    guess: GetSinglePlayerGameResponseRoundsInnerResultGuessFromJSON(json['guess']),
    target: GetSinglePlayerGameResponseRoundsInnerResultTargetFromJSON(json['target']),
    distanceKm: json['distanceKm'],
    score: json['score'],
    completedAt: new Date(json['completedAt']),
  }
}

export function GetSinglePlayerGameResponseRoundsInnerResultToJSON(
  json: any,
): GetSinglePlayerGameResponseRoundsInnerResult {
  return GetSinglePlayerGameResponseRoundsInnerResultToJSONTyped(json, false)
}

export function GetSinglePlayerGameResponseRoundsInnerResultToJSONTyped(
  value?: GetSinglePlayerGameResponseRoundsInnerResult | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    guess: GetSinglePlayerGameResponseRoundsInnerResultGuessToJSON(value['guess']),
    target: GetSinglePlayerGameResponseRoundsInnerResultTargetToJSON(value['target']),
    distanceKm: value['distanceKm'],
    score: value['score'],
    completedAt: value['completedAt'].toISOString(),
  }
}
