/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetTodayDailyChallenge200ResponseGame } from './GetTodayDailyChallenge200ResponseGame'
import {
  GetTodayDailyChallenge200ResponseGameFromJSON,
  GetTodayDailyChallenge200ResponseGameFromJSONTyped,
  GetTodayDailyChallenge200ResponseGameToJSON,
  GetTodayDailyChallenge200ResponseGameToJSONTyped,
} from './GetTodayDailyChallenge200ResponseGame'

/**
 *
 * @export
 * @interface GetTodayDailyChallengeResponse
 */
export interface GetTodayDailyChallengeResponse {
  /**
   *
   * @type {Date}
   * @memberof GetTodayDailyChallengeResponse
   */
  date: Date
  /**
   *
   * @type {string}
   * @memberof GetTodayDailyChallengeResponse
   */
  status: GetTodayDailyChallengeResponseStatusEnum
  /**
   *
   * @type {GetTodayDailyChallenge200ResponseGame}
   * @memberof GetTodayDailyChallengeResponse
   */
  game?: GetTodayDailyChallenge200ResponseGame
}

/**
 * @export
 */
export const GetTodayDailyChallengeResponseStatusEnum = {
  Available: 'available',
  Ongoing: 'ongoing',
  Completed: 'completed',
} as const
export type GetTodayDailyChallengeResponseStatusEnum =
  (typeof GetTodayDailyChallengeResponseStatusEnum)[keyof typeof GetTodayDailyChallengeResponseStatusEnum]

/**
 * Check if a given object implements the GetTodayDailyChallengeResponse interface.
 */
export function instanceOfGetTodayDailyChallengeResponse(
  value: object,
): value is GetTodayDailyChallengeResponse {
  if (!('date' in value) || value['date'] === undefined) return false
  if (!('status' in value) || value['status'] === undefined) return false
  return true
}

export function GetTodayDailyChallengeResponseFromJSON(json: any): GetTodayDailyChallengeResponse {
  return GetTodayDailyChallengeResponseFromJSONTyped(json, false)
}

export function GetTodayDailyChallengeResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetTodayDailyChallengeResponse {
  if (json == null) {
    return json
  }
  return {
    date: new Date(json['date']),
    status: json['status'],
    game:
      json['game'] == null
        ? undefined
        : GetTodayDailyChallenge200ResponseGameFromJSON(json['game']),
  }
}

export function GetTodayDailyChallengeResponseToJSON(json: any): GetTodayDailyChallengeResponse {
  return GetTodayDailyChallengeResponseToJSONTyped(json, false)
}

export function GetTodayDailyChallengeResponseToJSONTyped(
  value?: GetTodayDailyChallengeResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    date: value['date'].toISOString().substring(0, 10),
    status: value['status'],
    game: GetTodayDailyChallenge200ResponseGameToJSON(value['game']),
  }
}
