/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetTodayDailyChallenge200ResponseGameRoundsInnerResult } from './GetTodayDailyChallenge200ResponseGameRoundsInnerResult'
import {
  GetTodayDailyChallenge200ResponseGameRoundsInnerResultFromJSON,
  GetTodayDailyChallenge200ResponseGameRoundsInnerResultFromJSONTyped,
  GetTodayDailyChallenge200ResponseGameRoundsInnerResultToJSON,
  GetTodayDailyChallenge200ResponseGameRoundsInnerResultToJSONTyped,
} from './GetTodayDailyChallenge200ResponseGameRoundsInnerResult'

/**
 *
 * @export
 * @interface GetTodayDailyChallenge200ResponseGameRoundsInner
 */
export interface GetTodayDailyChallenge200ResponseGameRoundsInner {
  /**
   *
   * @type {number}
   * @memberof GetTodayDailyChallenge200ResponseGameRoundsInner
   */
  roundNumber: number
  /**
   *
   * @type {string}
   * @memberof GetTodayDailyChallenge200ResponseGameRoundsInner
   */
  imageId: string
  /**
   *
   * @type {Date}
   * @memberof GetTodayDailyChallenge200ResponseGameRoundsInner
   */
  startedAt: Date
  /**
   *
   * @type {GetTodayDailyChallenge200ResponseGameRoundsInnerResult}
   * @memberof GetTodayDailyChallenge200ResponseGameRoundsInner
   */
  result?: GetTodayDailyChallenge200ResponseGameRoundsInnerResult
}

/**
 * Check if a given object implements the GetTodayDailyChallenge200ResponseGameRoundsInner interface.
 */
export function instanceOfGetTodayDailyChallenge200ResponseGameRoundsInner(
  value: object,
): value is GetTodayDailyChallenge200ResponseGameRoundsInner {
  if (!('roundNumber' in value) || value['roundNumber'] === undefined) return false
  if (!('imageId' in value) || value['imageId'] === undefined) return false
  if (!('startedAt' in value) || value['startedAt'] === undefined) return false
  return true
}

export function GetTodayDailyChallenge200ResponseGameRoundsInnerFromJSON(
  json: any,
): GetTodayDailyChallenge200ResponseGameRoundsInner {
  return GetTodayDailyChallenge200ResponseGameRoundsInnerFromJSONTyped(json, false)
}

export function GetTodayDailyChallenge200ResponseGameRoundsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetTodayDailyChallenge200ResponseGameRoundsInner {
  if (json == null) {
    return json
  }
  return {
    roundNumber: json['roundNumber'],
    imageId: json['imageId'],
    startedAt: new Date(json['startedAt']),
    result:
      json['result'] == null
        ? undefined
        : GetTodayDailyChallenge200ResponseGameRoundsInnerResultFromJSON(json['result']),
  }
}

export function GetTodayDailyChallenge200ResponseGameRoundsInnerToJSON(
  json: any,
): GetTodayDailyChallenge200ResponseGameRoundsInner {
  return GetTodayDailyChallenge200ResponseGameRoundsInnerToJSONTyped(json, false)
}

export function GetTodayDailyChallenge200ResponseGameRoundsInnerToJSONTyped(
  value?: GetTodayDailyChallenge200ResponseGameRoundsInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    roundNumber: value['roundNumber'],
    imageId: value['imageId'],
    startedAt: value['startedAt'].toISOString(),
    result: GetTodayDailyChallenge200ResponseGameRoundsInnerResultToJSON(value['result']),
  }
}
