/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetTodayDailyChallenge200ResponseGameRoundsInner } from './GetTodayDailyChallenge200ResponseGameRoundsInner'
import {
  GetTodayDailyChallenge200ResponseGameRoundsInnerFromJSON,
  GetTodayDailyChallenge200ResponseGameRoundsInnerFromJSONTyped,
  GetTodayDailyChallenge200ResponseGameRoundsInnerToJSON,
  GetTodayDailyChallenge200ResponseGameRoundsInnerToJSONTyped,
} from './GetTodayDailyChallenge200ResponseGameRoundsInner'

/**
 *
 * @export
 * @interface GetTodayDailyChallenge200ResponseGame
 */
export interface GetTodayDailyChallenge200ResponseGame {
  /**
   *
   * @type {string}
   * @memberof GetTodayDailyChallenge200ResponseGame
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof GetTodayDailyChallenge200ResponseGame
   */
  status: GetTodayDailyChallenge200ResponseGameStatusEnum
  /**
   *
   * @type {number}
   * @memberof GetTodayDailyChallenge200ResponseGame
   */
  currentRound: number
  /**
   *
   * @type {Array<GetTodayDailyChallenge200ResponseGameRoundsInner>}
   * @memberof GetTodayDailyChallenge200ResponseGame
   */
  rounds: Array<GetTodayDailyChallenge200ResponseGameRoundsInner>
  /**
   *
   * @type {Date}
   * @memberof GetTodayDailyChallenge200ResponseGame
   */
  createdAt: Date
  /**
   *
   * @type {Date}
   * @memberof GetTodayDailyChallenge200ResponseGame
   */
  completedAt?: Date
}

/**
 * @export
 */
export const GetTodayDailyChallenge200ResponseGameStatusEnum = {
  Ongoing: 'ongoing',
  Completed: 'completed',
} as const
export type GetTodayDailyChallenge200ResponseGameStatusEnum =
  (typeof GetTodayDailyChallenge200ResponseGameStatusEnum)[keyof typeof GetTodayDailyChallenge200ResponseGameStatusEnum]

/**
 * Check if a given object implements the GetTodayDailyChallenge200ResponseGame interface.
 */
export function instanceOfGetTodayDailyChallenge200ResponseGame(
  value: object,
): value is GetTodayDailyChallenge200ResponseGame {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('status' in value) || value['status'] === undefined) return false
  if (!('currentRound' in value) || value['currentRound'] === undefined) return false
  if (!('rounds' in value) || value['rounds'] === undefined) return false
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false
  return true
}

export function GetTodayDailyChallenge200ResponseGameFromJSON(
  json: any,
): GetTodayDailyChallenge200ResponseGame {
  return GetTodayDailyChallenge200ResponseGameFromJSONTyped(json, false)
}

export function GetTodayDailyChallenge200ResponseGameFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetTodayDailyChallenge200ResponseGame {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    status: json['status'],
    currentRound: json['currentRound'],
    rounds: (json['rounds'] as Array<any>).map(
      GetTodayDailyChallenge200ResponseGameRoundsInnerFromJSON,
    ),
    createdAt: new Date(json['createdAt']),
    completedAt: json['completedAt'] == null ? undefined : new Date(json['completedAt']),
  }
}

export function GetTodayDailyChallenge200ResponseGameToJSON(
  json: any,
): GetTodayDailyChallenge200ResponseGame {
  return GetTodayDailyChallenge200ResponseGameToJSONTyped(json, false)
}

export function GetTodayDailyChallenge200ResponseGameToJSONTyped(
  value?: GetTodayDailyChallenge200ResponseGame | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    status: value['status'],
    currentRound: value['currentRound'],
    rounds: (value['rounds'] as Array<any>).map(
      GetTodayDailyChallenge200ResponseGameRoundsInnerToJSON,
    ),
    createdAt: value['createdAt'].toISOString(),
    completedAt:
      value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
  }
}
