/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { GetTodayDailyChallenge200ResponseGame } from './GetTodayDailyChallenge200ResponseGame'
import {
  GetTodayDailyChallenge200ResponseGameFromJSON,
  GetTodayDailyChallenge200ResponseGameFromJSONTyped,
  GetTodayDailyChallenge200ResponseGameToJSON,
  GetTodayDailyChallenge200ResponseGameToJSONTyped,
} from './GetTodayDailyChallenge200ResponseGame'

/**
 *
 * @export
 * @interface GetTodayDailyChallenge200Response
 */
export interface GetTodayDailyChallenge200Response {
  /**
   *
   * @type {Date}
   * @memberof GetTodayDailyChallenge200Response
   */
  date: Date
  /**
   *
   * @type {string}
   * @memberof GetTodayDailyChallenge200Response
   */
  status: GetTodayDailyChallenge200ResponseStatusEnum
  /**
   *
   * @type {GetTodayDailyChallenge200ResponseGame}
   * @memberof GetTodayDailyChallenge200Response
   */
  game?: GetTodayDailyChallenge200ResponseGame
}

/**
 * @export
 */
export const GetTodayDailyChallenge200ResponseStatusEnum = {
  Available: 'available',
  Ongoing: 'ongoing',
  Completed: 'completed',
} as const
export type GetTodayDailyChallenge200ResponseStatusEnum =
  (typeof GetTodayDailyChallenge200ResponseStatusEnum)[keyof typeof GetTodayDailyChallenge200ResponseStatusEnum]

/**
 * Check if a given object implements the GetTodayDailyChallenge200Response interface.
 */
export function instanceOfGetTodayDailyChallenge200Response(
  value: object,
): value is GetTodayDailyChallenge200Response {
  if (!('date' in value) || value['date'] === undefined) return false
  if (!('status' in value) || value['status'] === undefined) return false
  return true
}

export function GetTodayDailyChallenge200ResponseFromJSON(
  json: any,
): GetTodayDailyChallenge200Response {
  return GetTodayDailyChallenge200ResponseFromJSONTyped(json, false)
}

export function GetTodayDailyChallenge200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetTodayDailyChallenge200Response {
  if (json == null) {
    return json
  }
  return {
    date: new Date(json['date']),
    status: json['status'],
    game:
      json['game'] == null
        ? undefined
        : GetTodayDailyChallenge200ResponseGameFromJSON(json['game']),
  }
}

export function GetTodayDailyChallenge200ResponseToJSON(
  json: any,
): GetTodayDailyChallenge200Response {
  return GetTodayDailyChallenge200ResponseToJSONTyped(json, false)
}

export function GetTodayDailyChallenge200ResponseToJSONTyped(
  value?: GetTodayDailyChallenge200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    date: value['date'].toISOString().substring(0, 10),
    status: value['status'],
    game: GetTodayDailyChallenge200ResponseGameToJSON(value['game']),
  }
}
