/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface GetWithFriendsGames200ResponseInner
 */
export interface GetWithFriendsGames200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof GetWithFriendsGames200ResponseInner
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof GetWithFriendsGames200ResponseInner
   */
  hostUserId: string
  /**
   *
   * @type {string}
   * @memberof GetWithFriendsGames200ResponseInner
   */
  hostDisplayName: string
  /**
   *
   * @type {string}
   * @memberof GetWithFriendsGames200ResponseInner
   */
  hostCountry: string | null
  /**
   *
   * @type {number}
   * @memberof GetWithFriendsGames200ResponseInner
   */
  rank: number
  /**
   *
   * @type {number}
   * @memberof GetWithFriendsGames200ResponseInner
   */
  playerCount: number
  /**
   *
   * @type {number}
   * @memberof GetWithFriendsGames200ResponseInner
   */
  totalScore: number
  /**
   *
   * @type {number}
   * @memberof GetWithFriendsGames200ResponseInner
   */
  totalDistanceKm: number | null
  /**
   *
   * @type {Date}
   * @memberof GetWithFriendsGames200ResponseInner
   */
  completedAt: Date
}

/**
 * Check if a given object implements the GetWithFriendsGames200ResponseInner interface.
 */
export function instanceOfGetWithFriendsGames200ResponseInner(
  value: object,
): value is GetWithFriendsGames200ResponseInner {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('hostUserId' in value) || value['hostUserId'] === undefined) return false
  if (!('hostDisplayName' in value) || value['hostDisplayName'] === undefined) return false
  if (!('hostCountry' in value) || value['hostCountry'] === undefined) return false
  if (!('rank' in value) || value['rank'] === undefined) return false
  if (!('playerCount' in value) || value['playerCount'] === undefined) return false
  if (!('totalScore' in value) || value['totalScore'] === undefined) return false
  if (!('totalDistanceKm' in value) || value['totalDistanceKm'] === undefined) return false
  if (!('completedAt' in value) || value['completedAt'] === undefined) return false
  return true
}

export function GetWithFriendsGames200ResponseInnerFromJSON(
  json: any,
): GetWithFriendsGames200ResponseInner {
  return GetWithFriendsGames200ResponseInnerFromJSONTyped(json, false)
}

export function GetWithFriendsGames200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetWithFriendsGames200ResponseInner {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    hostUserId: json['hostUserId'],
    hostDisplayName: json['hostDisplayName'],
    hostCountry: json['hostCountry'],
    rank: json['rank'],
    playerCount: json['playerCount'],
    totalScore: json['totalScore'],
    totalDistanceKm: json['totalDistanceKm'],
    completedAt: new Date(json['completedAt']),
  }
}

export function GetWithFriendsGames200ResponseInnerToJSON(
  json: any,
): GetWithFriendsGames200ResponseInner {
  return GetWithFriendsGames200ResponseInnerToJSONTyped(json, false)
}

export function GetWithFriendsGames200ResponseInnerToJSONTyped(
  value?: GetWithFriendsGames200ResponseInner | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    hostUserId: value['hostUserId'],
    hostDisplayName: value['hostDisplayName'],
    hostCountry: value['hostCountry'],
    rank: value['rank'],
    playerCount: value['playerCount'],
    totalScore: value['totalScore'],
    totalDistanceKm: value['totalDistanceKm'],
    completedAt: value['completedAt'].toISOString(),
  }
}
