/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface JoinWithFriendsGameResponse
 */
export interface JoinWithFriendsGameResponse {
  /**
   *
   * @type {string}
   * @memberof JoinWithFriendsGameResponse
   */
  id: string
}

/**
 * Check if a given object implements the JoinWithFriendsGameResponse interface.
 */
export function instanceOfJoinWithFriendsGameResponse(
  value: object,
): value is JoinWithFriendsGameResponse {
  if (!('id' in value) || value['id'] === undefined) return false
  return true
}

export function JoinWithFriendsGameResponseFromJSON(json: any): JoinWithFriendsGameResponse {
  return JoinWithFriendsGameResponseFromJSONTyped(json, false)
}

export function JoinWithFriendsGameResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): JoinWithFriendsGameResponse {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
  }
}

export function JoinWithFriendsGameResponseToJSON(json: any): JoinWithFriendsGameResponse {
  return JoinWithFriendsGameResponseToJSONTyped(json, false)
}

export function JoinWithFriendsGameResponseToJSONTyped(
  value?: JoinWithFriendsGameResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
  }
}
