/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface JoinWithFriendsGame200Response
 */
export interface JoinWithFriendsGame200Response {
  /**
   *
   * @type {string}
   * @memberof JoinWithFriendsGame200Response
   */
  id: string
}

/**
 * Check if a given object implements the JoinWithFriendsGame200Response interface.
 */
export function instanceOfJoinWithFriendsGame200Response(
  value: object,
): value is JoinWithFriendsGame200Response {
  if (!('id' in value) || value['id'] === undefined) return false
  return true
}

export function JoinWithFriendsGame200ResponseFromJSON(json: any): JoinWithFriendsGame200Response {
  return JoinWithFriendsGame200ResponseFromJSONTyped(json, false)
}

export function JoinWithFriendsGame200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): JoinWithFriendsGame200Response {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
  }
}

export function JoinWithFriendsGame200ResponseToJSON(json: any): JoinWithFriendsGame200Response {
  return JoinWithFriendsGame200ResponseToJSONTyped(json, false)
}

export function JoinWithFriendsGame200ResponseToJSONTyped(
  value?: JoinWithFriendsGame200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
  }
}
