/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface JoinWithFriendsGameRequest
 */
export interface JoinWithFriendsGameRequest {
  /**
   *
   * @type {string}
   * @memberof JoinWithFriendsGameRequest
   */
  roomKey: string
}

/**
 * Check if a given object implements the JoinWithFriendsGameRequest interface.
 */
export function instanceOfJoinWithFriendsGameRequest(
  value: object,
): value is JoinWithFriendsGameRequest {
  if (!('roomKey' in value) || value['roomKey'] === undefined) return false
  return true
}

export function JoinWithFriendsGameRequestFromJSON(json: any): JoinWithFriendsGameRequest {
  return JoinWithFriendsGameRequestFromJSONTyped(json, false)
}

export function JoinWithFriendsGameRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): JoinWithFriendsGameRequest {
  if (json == null) {
    return json
  }
  return {
    roomKey: json['roomKey'],
  }
}

export function JoinWithFriendsGameRequestToJSON(json: any): JoinWithFriendsGameRequest {
  return JoinWithFriendsGameRequestToJSONTyped(json, false)
}

export function JoinWithFriendsGameRequestToJSONTyped(
  value?: JoinWithFriendsGameRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    roomKey: value['roomKey'],
  }
}
