/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface StartDailyChallengeGameRoundResponse
 */
export interface StartDailyChallengeGameRoundResponse {
  /**
   *
   * @type {number}
   * @memberof StartDailyChallengeGameRoundResponse
   */
  roundNumber: number
  /**
   *
   * @type {string}
   * @memberof StartDailyChallengeGameRoundResponse
   */
  imageId: string
  /**
   *
   * @type {Date}
   * @memberof StartDailyChallengeGameRoundResponse
   */
  startedAt: Date
}

/**
 * Check if a given object implements the StartDailyChallengeGameRoundResponse interface.
 */
export function instanceOfStartDailyChallengeGameRoundResponse(
  value: object,
): value is StartDailyChallengeGameRoundResponse {
  if (!('roundNumber' in value) || value['roundNumber'] === undefined) return false
  if (!('imageId' in value) || value['imageId'] === undefined) return false
  if (!('startedAt' in value) || value['startedAt'] === undefined) return false
  return true
}

export function StartDailyChallengeGameRoundResponseFromJSON(
  json: any,
): StartDailyChallengeGameRoundResponse {
  return StartDailyChallengeGameRoundResponseFromJSONTyped(json, false)
}

export function StartDailyChallengeGameRoundResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StartDailyChallengeGameRoundResponse {
  if (json == null) {
    return json
  }
  return {
    roundNumber: json['roundNumber'],
    imageId: json['imageId'],
    startedAt: new Date(json['startedAt']),
  }
}

export function StartDailyChallengeGameRoundResponseToJSON(
  json: any,
): StartDailyChallengeGameRoundResponse {
  return StartDailyChallengeGameRoundResponseToJSONTyped(json, false)
}

export function StartDailyChallengeGameRoundResponseToJSONTyped(
  value?: StartDailyChallengeGameRoundResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    roundNumber: value['roundNumber'],
    imageId: value['imageId'],
    startedAt: value['startedAt'].toISOString(),
  }
}
