/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface StartSinglePlayerGameRound200Response
 */
export interface StartSinglePlayerGameRound200Response {
  /**
   *
   * @type {number}
   * @memberof StartSinglePlayerGameRound200Response
   */
  roundNumber: number
  /**
   *
   * @type {string}
   * @memberof StartSinglePlayerGameRound200Response
   */
  imageId: string
  /**
   *
   * @type {Date}
   * @memberof StartSinglePlayerGameRound200Response
   */
  startedAt: Date
}

/**
 * Check if a given object implements the StartSinglePlayerGameRound200Response interface.
 */
export function instanceOfStartSinglePlayerGameRound200Response(
  value: object,
): value is StartSinglePlayerGameRound200Response {
  if (!('roundNumber' in value) || value['roundNumber'] === undefined) return false
  if (!('imageId' in value) || value['imageId'] === undefined) return false
  if (!('startedAt' in value) || value['startedAt'] === undefined) return false
  return true
}

export function StartSinglePlayerGameRound200ResponseFromJSON(
  json: any,
): StartSinglePlayerGameRound200Response {
  return StartSinglePlayerGameRound200ResponseFromJSONTyped(json, false)
}

export function StartSinglePlayerGameRound200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StartSinglePlayerGameRound200Response {
  if (json == null) {
    return json
  }
  return {
    roundNumber: json['roundNumber'],
    imageId: json['imageId'],
    startedAt: new Date(json['startedAt']),
  }
}

export function StartSinglePlayerGameRound200ResponseToJSON(
  json: any,
): StartSinglePlayerGameRound200Response {
  return StartSinglePlayerGameRound200ResponseToJSONTyped(json, false)
}

export function StartSinglePlayerGameRound200ResponseToJSONTyped(
  value?: StartSinglePlayerGameRound200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    roundNumber: value['roundNumber'],
    imageId: value['imageId'],
    startedAt: value['startedAt'].toISOString(),
  }
}
