/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UpdateUser200Response
 */
export interface UpdateUser200Response {
  /**
   *
   * @type {string}
   * @memberof UpdateUser200Response
   */
  userId: string
  /**
   *
   * @type {string}
   * @memberof UpdateUser200Response
   */
  displayName: string
  /**
   *
   * @type {string}
   * @memberof UpdateUser200Response
   */
  country: string | null
  /**
   *
   * @type {Date}
   * @memberof UpdateUser200Response
   */
  createdAt: Date
  /**
   *
   * @type {Date}
   * @memberof UpdateUser200Response
   */
  updatedAt: Date
}

/**
 * Check if a given object implements the UpdateUser200Response interface.
 */
export function instanceOfUpdateUser200Response(value: object): value is UpdateUser200Response {
  if (!('userId' in value) || value['userId'] === undefined) return false
  if (!('displayName' in value) || value['displayName'] === undefined) return false
  if (!('country' in value) || value['country'] === undefined) return false
  if (!('createdAt' in value) || value['createdAt'] === undefined) return false
  if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false
  return true
}

export function UpdateUser200ResponseFromJSON(json: any): UpdateUser200Response {
  return UpdateUser200ResponseFromJSONTyped(json, false)
}

export function UpdateUser200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateUser200Response {
  if (json == null) {
    return json
  }
  return {
    userId: json['userId'],
    displayName: json['displayName'],
    country: json['country'],
    createdAt: new Date(json['createdAt']),
    updatedAt: new Date(json['updatedAt']),
  }
}

export function UpdateUser200ResponseToJSON(json: any): UpdateUser200Response {
  return UpdateUser200ResponseToJSONTyped(json, false)
}

export function UpdateUser200ResponseToJSONTyped(
  value?: UpdateUser200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    userId: value['userId'],
    displayName: value['displayName'],
    country: value['country'],
    createdAt: value['createdAt'].toISOString(),
    updatedAt: value['updatedAt'].toISOString(),
  }
}
