/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  displayName?: string
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  country?: string | null
  /**
   *
   * @type {string}
   * @memberof UpdateUserRequest
   */
  distanceUnit?: UpdateUserRequestDistanceUnitEnum
}

/**
 * @export
 */
export const UpdateUserRequestDistanceUnitEnum = {
  Km: 'km',
  Mile: 'mile',
} as const
export type UpdateUserRequestDistanceUnitEnum =
  (typeof UpdateUserRequestDistanceUnitEnum)[keyof typeof UpdateUserRequestDistanceUnitEnum]

/**
 * Check if a given object implements the UpdateUserRequest interface.
 */
export function instanceOfUpdateUserRequest(value: object): value is UpdateUserRequest {
  return true
}

export function UpdateUserRequestFromJSON(json: any): UpdateUserRequest {
  return UpdateUserRequestFromJSONTyped(json, false)
}

export function UpdateUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateUserRequest {
  if (json == null) {
    return json
  }
  return {
    displayName: json['displayName'] == null ? undefined : json['displayName'],
    country: json['country'] == null ? undefined : json['country'],
    distanceUnit: json['distanceUnit'] == null ? undefined : json['distanceUnit'],
  }
}

export function UpdateUserRequestToJSON(json: any): UpdateUserRequest {
  return UpdateUserRequestToJSONTyped(json, false)
}

export function UpdateUserRequestToJSONTyped(
  value?: UpdateUserRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    displayName: value['displayName'],
    country: value['country'],
    distanceUnit: value['distanceUnit'],
  }
}
