/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  CreateDailyChallengeGame200Response,
  CreateDailyChallengeGameGuess200Response,
  CreateDailyChallengeGameGuessRequest,
  CreateSinglePlayerGame201Response,
  CreateSinglePlayerGameGuess200Response,
  CreateSinglePlayerGameGuessRequest,
  CreateUser200Response,
  CreateUserRequest,
  CreateWithFriendsGame201Response,
  CreateWithFriendsGameGuessRequest,
  GetCurrentUser200Response,
  GetDailyChallengeGames200ResponseInner,
  GetDailyChallengeLeaderboard200ResponseInner,
  GetSinglePlayerGames200ResponseInner,
  GetSinglePlayerGames400Response,
  GetSinglePlayerGames401Response,
  GetTodayDailyChallenge200Response,
  GetUser200Response,
  GetWithFriendsGames200ResponseInner,
  JoinWithFriendsGame200Response,
  JoinWithFriendsGameRequest,
  StartDailyChallengeGameRound200Response,
  StartSinglePlayerGameRound200Response,
  UpdateUser200Response,
  UpdateUserRequest,
} from '../models/index'
import {
  CreateDailyChallengeGame200ResponseFromJSON,
  CreateDailyChallengeGame200ResponseToJSON,
  CreateDailyChallengeGameGuess200ResponseFromJSON,
  CreateDailyChallengeGameGuess200ResponseToJSON,
  CreateDailyChallengeGameGuessRequestFromJSON,
  CreateDailyChallengeGameGuessRequestToJSON,
  CreateSinglePlayerGame201ResponseFromJSON,
  CreateSinglePlayerGame201ResponseToJSON,
  CreateSinglePlayerGameGuess200ResponseFromJSON,
  CreateSinglePlayerGameGuess200ResponseToJSON,
  CreateSinglePlayerGameGuessRequestFromJSON,
  CreateSinglePlayerGameGuessRequestToJSON,
  CreateUser200ResponseFromJSON,
  CreateUser200ResponseToJSON,
  CreateUserRequestFromJSON,
  CreateUserRequestToJSON,
  CreateWithFriendsGame201ResponseFromJSON,
  CreateWithFriendsGame201ResponseToJSON,
  CreateWithFriendsGameGuessRequestFromJSON,
  CreateWithFriendsGameGuessRequestToJSON,
  GetCurrentUser200ResponseFromJSON,
  GetCurrentUser200ResponseToJSON,
  GetDailyChallengeGames200ResponseInnerFromJSON,
  GetDailyChallengeGames200ResponseInnerToJSON,
  GetDailyChallengeLeaderboard200ResponseInnerFromJSON,
  GetDailyChallengeLeaderboard200ResponseInnerToJSON,
  GetSinglePlayerGames200ResponseInnerFromJSON,
  GetSinglePlayerGames200ResponseInnerToJSON,
  GetSinglePlayerGames400ResponseFromJSON,
  GetSinglePlayerGames400ResponseToJSON,
  GetSinglePlayerGames401ResponseFromJSON,
  GetSinglePlayerGames401ResponseToJSON,
  GetTodayDailyChallenge200ResponseFromJSON,
  GetTodayDailyChallenge200ResponseToJSON,
  GetUser200ResponseFromJSON,
  GetUser200ResponseToJSON,
  GetWithFriendsGames200ResponseInnerFromJSON,
  GetWithFriendsGames200ResponseInnerToJSON,
  JoinWithFriendsGame200ResponseFromJSON,
  JoinWithFriendsGame200ResponseToJSON,
  JoinWithFriendsGameRequestFromJSON,
  JoinWithFriendsGameRequestToJSON,
  StartDailyChallengeGameRound200ResponseFromJSON,
  StartDailyChallengeGameRound200ResponseToJSON,
  StartSinglePlayerGameRound200ResponseFromJSON,
  StartSinglePlayerGameRound200ResponseToJSON,
  UpdateUser200ResponseFromJSON,
  UpdateUser200ResponseToJSON,
  UpdateUserRequestFromJSON,
  UpdateUserRequestToJSON,
} from '../models/index'

export interface CreateDailyChallengeGameGuessOperationRequest {
  gameId: string
  roundNumber: number
  createDailyChallengeGameGuessRequest: CreateDailyChallengeGameGuessRequest
}

export interface CreateSinglePlayerGameGuessOperationRequest {
  gameId: string
  roundNumber: number
  createSinglePlayerGameGuessRequest: CreateSinglePlayerGameGuessRequest
}

export interface CreateUserOperationRequest {
  createUserRequest?: CreateUserRequest
}

export interface CreateWithFriendsGameGuessOperationRequest {
  gameId: string
  roundNumber: number
  createWithFriendsGameGuessRequest: CreateWithFriendsGameGuessRequest
}

export interface GetDailyChallengeGameRequest {
  gameId: string
}

export interface GetDailyChallengeGamesRequest {
  limit?: number
  sortBy?: GetDailyChallengeGamesSortByEnum
  orderBy?: GetDailyChallengeGamesOrderByEnum
}

export interface GetDailyChallengeLeaderboardRequest {
  date: Date
}

export interface GetSinglePlayerGameRequest {
  gameId: string
}

export interface GetSinglePlayerGamesRequest {
  limit?: number
  sortBy?: GetSinglePlayerGamesSortByEnum
  orderBy?: GetSinglePlayerGamesOrderByEnum
}

export interface GetUserRequest {
  userId: string
}

export interface GetWithFriendsGamesRequest {
  limit?: number
  sortBy?: GetWithFriendsGamesSortByEnum
  orderBy?: GetWithFriendsGamesOrderByEnum
}

export interface JoinWithFriendsGameOperationRequest {
  joinWithFriendsGameRequest: JoinWithFriendsGameRequest
}

export interface StartDailyChallengeGameRoundRequest {
  gameId: string
  roundNumber: number
}

export interface StartSinglePlayerGameRoundRequest {
  gameId: string
  roundNumber: number
}

export interface StartWithFriendsGameRequest {
  gameId: string
}

export interface UpdateUserOperationRequest {
  updateUserRequest: UpdateUserRequest
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   * Create or resume today\'s daily challenge game
   */
  async createDailyChallengeGameRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateDailyChallengeGame200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/daily-challenge-games`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateDailyChallengeGame200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Create or resume today\'s daily challenge game
   */
  async createDailyChallengeGame(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateDailyChallengeGame200Response> {
    const response = await this.createDailyChallengeGameRaw(initOverrides)
    return await response.value()
  }

  /**
   * Complete a daily challenge round with a guess or timeout
   */
  async createDailyChallengeGameGuessRaw(
    requestParameters: CreateDailyChallengeGameGuessOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateDailyChallengeGameGuess200Response>> {
    if (requestParameters['gameId'] == null) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter "gameId" was null or undefined when calling createDailyChallengeGameGuess().',
      )
    }

    if (requestParameters['roundNumber'] == null) {
      throw new runtime.RequiredError(
        'roundNumber',
        'Required parameter "roundNumber" was null or undefined when calling createDailyChallengeGameGuess().',
      )
    }

    if (requestParameters['createDailyChallengeGameGuessRequest'] == null) {
      throw new runtime.RequiredError(
        'createDailyChallengeGameGuessRequest',
        'Required parameter "createDailyChallengeGameGuessRequest" was null or undefined when calling createDailyChallengeGameGuess().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/daily-challenge-games/{gameId}/rounds/{roundNumber}/guesses`
    urlPath = urlPath.replace(
      `{${'gameId'}}`,
      encodeURIComponent(String(requestParameters['gameId'])),
    )
    urlPath = urlPath.replace(
      `{${'roundNumber'}}`,
      encodeURIComponent(String(requestParameters['roundNumber'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateDailyChallengeGameGuessRequestToJSON(
          requestParameters['createDailyChallengeGameGuessRequest'],
        ),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateDailyChallengeGameGuess200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Complete a daily challenge round with a guess or timeout
   */
  async createDailyChallengeGameGuess(
    requestParameters: CreateDailyChallengeGameGuessOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateDailyChallengeGameGuess200Response> {
    const response = await this.createDailyChallengeGameGuessRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Create a single-player game
   */
  async createSinglePlayerGameRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateSinglePlayerGame201Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/single-player-games`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateSinglePlayerGame201ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Create a single-player game
   */
  async createSinglePlayerGame(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateSinglePlayerGame201Response> {
    const response = await this.createSinglePlayerGameRaw(initOverrides)
    return await response.value()
  }

  /**
   * Complete a single-player round with a guess or timeout
   */
  async createSinglePlayerGameGuessRaw(
    requestParameters: CreateSinglePlayerGameGuessOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateSinglePlayerGameGuess200Response>> {
    if (requestParameters['gameId'] == null) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter "gameId" was null or undefined when calling createSinglePlayerGameGuess().',
      )
    }

    if (requestParameters['roundNumber'] == null) {
      throw new runtime.RequiredError(
        'roundNumber',
        'Required parameter "roundNumber" was null or undefined when calling createSinglePlayerGameGuess().',
      )
    }

    if (requestParameters['createSinglePlayerGameGuessRequest'] == null) {
      throw new runtime.RequiredError(
        'createSinglePlayerGameGuessRequest',
        'Required parameter "createSinglePlayerGameGuessRequest" was null or undefined when calling createSinglePlayerGameGuess().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/single-player-games/{gameId}/rounds/{roundNumber}/guesses`
    urlPath = urlPath.replace(
      `{${'gameId'}}`,
      encodeURIComponent(String(requestParameters['gameId'])),
    )
    urlPath = urlPath.replace(
      `{${'roundNumber'}}`,
      encodeURIComponent(String(requestParameters['roundNumber'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateSinglePlayerGameGuessRequestToJSON(
          requestParameters['createSinglePlayerGameGuessRequest'],
        ),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateSinglePlayerGameGuess200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Complete a single-player round with a guess or timeout
   */
  async createSinglePlayerGameGuess(
    requestParameters: CreateSinglePlayerGameGuessOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateSinglePlayerGameGuess200Response> {
    const response = await this.createSinglePlayerGameGuessRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Create the current user if needed
   */
  async createUserRaw(
    requestParameters: CreateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateUser200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/me`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateUserRequestToJSON(requestParameters['createUserRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Create the current user if needed
   */
  async createUser(
    requestParameters: CreateUserOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateUser200Response> {
    const response = await this.createUserRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Create a with-friends game
   */
  async createWithFriendsGameRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateWithFriendsGame201Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/with-friends-games`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateWithFriendsGame201ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Create a with-friends game
   */
  async createWithFriendsGame(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateWithFriendsGame201Response> {
    const response = await this.createWithFriendsGameRaw(initOverrides)
    return await response.value()
  }

  /**
   * Submit a with-friends game guess
   */
  async createWithFriendsGameGuessRaw(
    requestParameters: CreateWithFriendsGameGuessOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['gameId'] == null) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter "gameId" was null or undefined when calling createWithFriendsGameGuess().',
      )
    }

    if (requestParameters['roundNumber'] == null) {
      throw new runtime.RequiredError(
        'roundNumber',
        'Required parameter "roundNumber" was null or undefined when calling createWithFriendsGameGuess().',
      )
    }

    if (requestParameters['createWithFriendsGameGuessRequest'] == null) {
      throw new runtime.RequiredError(
        'createWithFriendsGameGuessRequest',
        'Required parameter "createWithFriendsGameGuessRequest" was null or undefined when calling createWithFriendsGameGuess().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/with-friends-games/{gameId}/rounds/{roundNumber}/guesses`
    urlPath = urlPath.replace(
      `{${'gameId'}}`,
      encodeURIComponent(String(requestParameters['gameId'])),
    )
    urlPath = urlPath.replace(
      `{${'roundNumber'}}`,
      encodeURIComponent(String(requestParameters['roundNumber'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateWithFriendsGameGuessRequestToJSON(
          requestParameters['createWithFriendsGameGuessRequest'],
        ),
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Submit a with-friends game guess
   */
  async createWithFriendsGameGuess(
    requestParameters: CreateWithFriendsGameGuessOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.createWithFriendsGameGuessRaw(requestParameters, initOverrides)
  }

  /**
   * Delete the current user
   */
  async deleteUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/me`

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Delete the current user
   */
  async deleteUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.deleteUserRaw(initOverrides)
  }

  /**
   * Get the current user
   */
  async getCurrentUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetCurrentUser200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/me`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetCurrentUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get the current user
   */
  async getCurrentUser(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetCurrentUser200Response> {
    const response = await this.getCurrentUserRaw(initOverrides)
    return await response.value()
  }

  /**
   * Get an owned completed daily challenge game
   */
  async getDailyChallengeGameRaw(
    requestParameters: GetDailyChallengeGameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateDailyChallengeGame200Response>> {
    if (requestParameters['gameId'] == null) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter "gameId" was null or undefined when calling getDailyChallengeGame().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/daily-challenge-games/{gameId}`
    urlPath = urlPath.replace(
      `{${'gameId'}}`,
      encodeURIComponent(String(requestParameters['gameId'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateDailyChallengeGame200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get an owned completed daily challenge game
   */
  async getDailyChallengeGame(
    requestParameters: GetDailyChallengeGameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateDailyChallengeGame200Response> {
    const response = await this.getDailyChallengeGameRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * List the current user\'s recent completed daily challenges
   */
  async getDailyChallengeGamesRaw(
    requestParameters: GetDailyChallengeGamesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<GetDailyChallengeGames200ResponseInner>>> {
    const queryParameters: any = {}

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit']
    }

    if (requestParameters['sortBy'] != null) {
      queryParameters['sort_by'] = requestParameters['sortBy']
    }

    if (requestParameters['orderBy'] != null) {
      queryParameters['order_by'] = requestParameters['orderBy']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/daily-challenge-games`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GetDailyChallengeGames200ResponseInnerFromJSON),
    )
  }

  /**
   * List the current user\'s recent completed daily challenges
   */
  async getDailyChallengeGames(
    requestParameters: GetDailyChallengeGamesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GetDailyChallengeGames200ResponseInner>> {
    const response = await this.getDailyChallengeGamesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Get the leaderboard for a recent daily challenge
   */
  async getDailyChallengeLeaderboardRaw(
    requestParameters: GetDailyChallengeLeaderboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<GetDailyChallengeLeaderboard200ResponseInner>>> {
    if (requestParameters['date'] == null) {
      throw new runtime.RequiredError(
        'date',
        'Required parameter "date" was null or undefined when calling getDailyChallengeLeaderboard().',
      )
    }

    const queryParameters: any = {}

    if (requestParameters['date'] != null) {
      queryParameters['date'] = (requestParameters['date'] as any).toISOString().substring(0, 10)
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/daily-challenge-games/leaderboard`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GetDailyChallengeLeaderboard200ResponseInnerFromJSON),
    )
  }

  /**
   * Get the leaderboard for a recent daily challenge
   */
  async getDailyChallengeLeaderboard(
    requestParameters: GetDailyChallengeLeaderboardRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GetDailyChallengeLeaderboard200ResponseInner>> {
    const response = await this.getDailyChallengeLeaderboardRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Get an owned single-player game
   */
  async getSinglePlayerGameRaw(
    requestParameters: GetSinglePlayerGameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateSinglePlayerGame201Response>> {
    if (requestParameters['gameId'] == null) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter "gameId" was null or undefined when calling getSinglePlayerGame().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/single-player-games/{gameId}`
    urlPath = urlPath.replace(
      `{${'gameId'}}`,
      encodeURIComponent(String(requestParameters['gameId'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateSinglePlayerGame201ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get an owned single-player game
   */
  async getSinglePlayerGame(
    requestParameters: GetSinglePlayerGameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateSinglePlayerGame201Response> {
    const response = await this.getSinglePlayerGameRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * List the current user\'s completed single-player games
   */
  async getSinglePlayerGamesRaw(
    requestParameters: GetSinglePlayerGamesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<GetSinglePlayerGames200ResponseInner>>> {
    const queryParameters: any = {}

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit']
    }

    if (requestParameters['sortBy'] != null) {
      queryParameters['sort_by'] = requestParameters['sortBy']
    }

    if (requestParameters['orderBy'] != null) {
      queryParameters['order_by'] = requestParameters['orderBy']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/single-player-games`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GetSinglePlayerGames200ResponseInnerFromJSON),
    )
  }

  /**
   * List the current user\'s completed single-player games
   */
  async getSinglePlayerGames(
    requestParameters: GetSinglePlayerGamesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GetSinglePlayerGames200ResponseInner>> {
    const response = await this.getSinglePlayerGamesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Get today\'s daily challenge availability and attempt
   */
  async getTodayDailyChallengeRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetTodayDailyChallenge200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/daily-challenge-games/today`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetTodayDailyChallenge200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get today\'s daily challenge availability and attempt
   */
  async getTodayDailyChallenge(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetTodayDailyChallenge200Response> {
    const response = await this.getTodayDailyChallengeRaw(initOverrides)
    return await response.value()
  }

  /**
   * Get a user profile
   */
  async getUserRaw(
    requestParameters: GetUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetUser200Response>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getUser().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/{userId}`
    urlPath = urlPath.replace(
      `{${'userId'}}`,
      encodeURIComponent(String(requestParameters['userId'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get a user profile
   */
  async getUser(
    requestParameters: GetUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetUser200Response> {
    const response = await this.getUserRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * List the current user\'s recent completed with-friends games
   */
  async getWithFriendsGamesRaw(
    requestParameters: GetWithFriendsGamesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<GetWithFriendsGames200ResponseInner>>> {
    const queryParameters: any = {}

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit']
    }

    if (requestParameters['sortBy'] != null) {
      queryParameters['sort_by'] = requestParameters['sortBy']
    }

    if (requestParameters['orderBy'] != null) {
      queryParameters['order_by'] = requestParameters['orderBy']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/with-friends-games`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GetWithFriendsGames200ResponseInnerFromJSON),
    )
  }

  /**
   * List the current user\'s recent completed with-friends games
   */
  async getWithFriendsGames(
    requestParameters: GetWithFriendsGamesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GetWithFriendsGames200ResponseInner>> {
    const response = await this.getWithFriendsGamesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Join a waiting with-friends game
   */
  async joinWithFriendsGameRaw(
    requestParameters: JoinWithFriendsGameOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<JoinWithFriendsGame200Response>> {
    if (requestParameters['joinWithFriendsGameRequest'] == null) {
      throw new runtime.RequiredError(
        'joinWithFriendsGameRequest',
        'Required parameter "joinWithFriendsGameRequest" was null or undefined when calling joinWithFriendsGame().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/with-friends-games/join`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: JoinWithFriendsGameRequestToJSON(requestParameters['joinWithFriendsGameRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      JoinWithFriendsGame200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Join a waiting with-friends game
   */
  async joinWithFriendsGame(
    requestParameters: JoinWithFriendsGameOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<JoinWithFriendsGame200Response> {
    const response = await this.joinWithFriendsGameRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Start the next daily challenge round
   */
  async startDailyChallengeGameRoundRaw(
    requestParameters: StartDailyChallengeGameRoundRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StartDailyChallengeGameRound200Response>> {
    if (requestParameters['gameId'] == null) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter "gameId" was null or undefined when calling startDailyChallengeGameRound().',
      )
    }

    if (requestParameters['roundNumber'] == null) {
      throw new runtime.RequiredError(
        'roundNumber',
        'Required parameter "roundNumber" was null or undefined when calling startDailyChallengeGameRound().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/daily-challenge-games/{gameId}/rounds/{roundNumber}/start`
    urlPath = urlPath.replace(
      `{${'gameId'}}`,
      encodeURIComponent(String(requestParameters['gameId'])),
    )
    urlPath = urlPath.replace(
      `{${'roundNumber'}}`,
      encodeURIComponent(String(requestParameters['roundNumber'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      StartDailyChallengeGameRound200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Start the next daily challenge round
   */
  async startDailyChallengeGameRound(
    requestParameters: StartDailyChallengeGameRoundRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StartDailyChallengeGameRound200Response> {
    const response = await this.startDailyChallengeGameRoundRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Start the next single-player round
   */
  async startSinglePlayerGameRoundRaw(
    requestParameters: StartSinglePlayerGameRoundRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StartSinglePlayerGameRound200Response>> {
    if (requestParameters['gameId'] == null) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter "gameId" was null or undefined when calling startSinglePlayerGameRound().',
      )
    }

    if (requestParameters['roundNumber'] == null) {
      throw new runtime.RequiredError(
        'roundNumber',
        'Required parameter "roundNumber" was null or undefined when calling startSinglePlayerGameRound().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/single-player-games/{gameId}/rounds/{roundNumber}/start`
    urlPath = urlPath.replace(
      `{${'gameId'}}`,
      encodeURIComponent(String(requestParameters['gameId'])),
    )
    urlPath = urlPath.replace(
      `{${'roundNumber'}}`,
      encodeURIComponent(String(requestParameters['roundNumber'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      StartSinglePlayerGameRound200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Start the next single-player round
   */
  async startSinglePlayerGameRound(
    requestParameters: StartSinglePlayerGameRoundRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StartSinglePlayerGameRound200Response> {
    const response = await this.startSinglePlayerGameRoundRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Start a with-friends game
   */
  async startWithFriendsGameRaw(
    requestParameters: StartWithFriendsGameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['gameId'] == null) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter "gameId" was null or undefined when calling startWithFriendsGame().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/with-friends-games/{gameId}/start`
    urlPath = urlPath.replace(
      `{${'gameId'}}`,
      encodeURIComponent(String(requestParameters['gameId'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Start a with-friends game
   */
  async startWithFriendsGame(
    requestParameters: StartWithFriendsGameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.startWithFriendsGameRaw(requestParameters, initOverrides)
  }

  /**
   * Update the current user
   */
  async updateUserRaw(
    requestParameters: UpdateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UpdateUser200Response>> {
    if (requestParameters['updateUserRequest'] == null) {
      throw new runtime.RequiredError(
        'updateUserRequest',
        'Required parameter "updateUserRequest" was null or undefined when calling updateUser().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/me`

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateUserRequestToJSON(requestParameters['updateUserRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UpdateUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Update the current user
   */
  async updateUser(
    requestParameters: UpdateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UpdateUser200Response> {
    const response = await this.updateUserRaw(requestParameters, initOverrides)
    return await response.value()
  }
}

/**
 * @export
 */
export const GetDailyChallengeGamesSortByEnum = {
  CreatedAt: 'created_at',
  CompletedAt: 'completed_at',
} as const
export type GetDailyChallengeGamesSortByEnum =
  (typeof GetDailyChallengeGamesSortByEnum)[keyof typeof GetDailyChallengeGamesSortByEnum]
/**
 * @export
 */
export const GetDailyChallengeGamesOrderByEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const
export type GetDailyChallengeGamesOrderByEnum =
  (typeof GetDailyChallengeGamesOrderByEnum)[keyof typeof GetDailyChallengeGamesOrderByEnum]
/**
 * @export
 */
export const GetSinglePlayerGamesSortByEnum = {
  CreatedAt: 'created_at',
  CompletedAt: 'completed_at',
} as const
export type GetSinglePlayerGamesSortByEnum =
  (typeof GetSinglePlayerGamesSortByEnum)[keyof typeof GetSinglePlayerGamesSortByEnum]
/**
 * @export
 */
export const GetSinglePlayerGamesOrderByEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const
export type GetSinglePlayerGamesOrderByEnum =
  (typeof GetSinglePlayerGamesOrderByEnum)[keyof typeof GetSinglePlayerGamesOrderByEnum]
/**
 * @export
 */
export const GetWithFriendsGamesSortByEnum = {
  CreatedAt: 'created_at',
  CompletedAt: 'completed_at',
} as const
export type GetWithFriendsGamesSortByEnum =
  (typeof GetWithFriendsGamesSortByEnum)[keyof typeof GetWithFriendsGamesSortByEnum]
/**
 * @export
 */
export const GetWithFriendsGamesOrderByEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const
export type GetWithFriendsGamesOrderByEnum =
  (typeof GetWithFriendsGamesOrderByEnum)[keyof typeof GetWithFriendsGamesOrderByEnum]
