/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  CreateUser200Response,
  CreateUserRequest,
  GetCurrentUser200Response,
  GetCurrentUser401Response,
  GetCurrentUser404Response,
  GetUser200Response,
  UpdateUser200Response,
  UpdateUserRequest,
} from '../models/index'
import {
  CreateUser200ResponseFromJSON,
  CreateUser200ResponseToJSON,
  CreateUserRequestFromJSON,
  CreateUserRequestToJSON,
  GetCurrentUser200ResponseFromJSON,
  GetCurrentUser200ResponseToJSON,
  GetCurrentUser401ResponseFromJSON,
  GetCurrentUser401ResponseToJSON,
  GetCurrentUser404ResponseFromJSON,
  GetCurrentUser404ResponseToJSON,
  GetUser200ResponseFromJSON,
  GetUser200ResponseToJSON,
  UpdateUser200ResponseFromJSON,
  UpdateUser200ResponseToJSON,
  UpdateUserRequestFromJSON,
  UpdateUserRequestToJSON,
} from '../models/index'

export interface CreateUserOperationRequest {
  createUserRequest?: CreateUserRequest
}

export interface GetUserRequest {
  userId: string
}

export interface UpdateUserOperationRequest {
  updateUserRequest: UpdateUserRequest
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   * Create the current user if needed
   */
  async createUserRaw(
    requestParameters: CreateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateUser200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/me`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateUserRequestToJSON(requestParameters['createUserRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Create the current user if needed
   */
  async createUser(
    requestParameters: CreateUserOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateUser200Response> {
    const response = await this.createUserRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Delete the current user
   */
  async deleteUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/me`

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Delete the current user
   */
  async deleteUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.deleteUserRaw(initOverrides)
  }

  /**
   * Get the current user
   */
  async getCurrentUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetCurrentUser200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/me`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetCurrentUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get the current user
   */
  async getCurrentUser(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetCurrentUser200Response> {
    const response = await this.getCurrentUserRaw(initOverrides)
    return await response.value()
  }

  /**
   * Get a user profile
   */
  async getUserRaw(
    requestParameters: GetUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetUser200Response>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getUser().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/{userId}`
    urlPath = urlPath.replace(
      `{${'userId'}}`,
      encodeURIComponent(String(requestParameters['userId'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get a user profile
   */
  async getUser(
    requestParameters: GetUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetUser200Response> {
    const response = await this.getUserRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Update the current user
   */
  async updateUserRaw(
    requestParameters: UpdateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UpdateUser200Response>> {
    if (requestParameters['updateUserRequest'] == null) {
      throw new runtime.RequiredError(
        'updateUserRequest',
        'Required parameter "updateUserRequest" was null or undefined when calling updateUser().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/me`

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateUserRequestToJSON(requestParameters['updateUserRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UpdateUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Update the current user
   */
  async updateUser(
    requestParameters: UpdateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UpdateUser200Response> {
    const response = await this.updateUserRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
