/* tslint:disable */
/* eslint-disable */
/**
 * GeoGuessLite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type {
  CreateDailyChallengeGame200Response,
  CreateDailyChallengeGameGuess200Response,
  CreateDailyChallengeGameGuessRequest,
  CreateSinglePlayerGame201Response,
  CreateSinglePlayerGameGuess200Response,
  CreateSinglePlayerGameGuessRequest,
  CreateUser200Response,
  CreateUserRequest,
  GetCurrentUser200Response,
  GetSinglePlayerGames200ResponseInner,
  GetSinglePlayerGames400Response,
  GetSinglePlayerGames401Response,
  GetTodayDailyChallenge200Response,
  GetUser200Response,
  StartDailyChallengeGameRound200Response,
  StartSinglePlayerGameRound200Response,
  UpdateUser200Response,
  UpdateUserRequest,
} from '../models/index'
import {
  CreateDailyChallengeGame200ResponseFromJSON,
  CreateDailyChallengeGame200ResponseToJSON,
  CreateDailyChallengeGameGuess200ResponseFromJSON,
  CreateDailyChallengeGameGuess200ResponseToJSON,
  CreateDailyChallengeGameGuessRequestFromJSON,
  CreateDailyChallengeGameGuessRequestToJSON,
  CreateSinglePlayerGame201ResponseFromJSON,
  CreateSinglePlayerGame201ResponseToJSON,
  CreateSinglePlayerGameGuess200ResponseFromJSON,
  CreateSinglePlayerGameGuess200ResponseToJSON,
  CreateSinglePlayerGameGuessRequestFromJSON,
  CreateSinglePlayerGameGuessRequestToJSON,
  CreateUser200ResponseFromJSON,
  CreateUser200ResponseToJSON,
  CreateUserRequestFromJSON,
  CreateUserRequestToJSON,
  GetCurrentUser200ResponseFromJSON,
  GetCurrentUser200ResponseToJSON,
  GetSinglePlayerGames200ResponseInnerFromJSON,
  GetSinglePlayerGames200ResponseInnerToJSON,
  GetSinglePlayerGames400ResponseFromJSON,
  GetSinglePlayerGames400ResponseToJSON,
  GetSinglePlayerGames401ResponseFromJSON,
  GetSinglePlayerGames401ResponseToJSON,
  GetTodayDailyChallenge200ResponseFromJSON,
  GetTodayDailyChallenge200ResponseToJSON,
  GetUser200ResponseFromJSON,
  GetUser200ResponseToJSON,
  StartDailyChallengeGameRound200ResponseFromJSON,
  StartDailyChallengeGameRound200ResponseToJSON,
  StartSinglePlayerGameRound200ResponseFromJSON,
  StartSinglePlayerGameRound200ResponseToJSON,
  UpdateUser200ResponseFromJSON,
  UpdateUser200ResponseToJSON,
  UpdateUserRequestFromJSON,
  UpdateUserRequestToJSON,
} from '../models/index'

export interface CreateDailyChallengeGameGuessOperationRequest {
  gameId: string
  roundNumber: number
  createDailyChallengeGameGuessRequest: CreateDailyChallengeGameGuessRequest
}

export interface CreateSinglePlayerGameGuessOperationRequest {
  gameId: string
  roundNumber: number
  createSinglePlayerGameGuessRequest: CreateSinglePlayerGameGuessRequest
}

export interface CreateUserOperationRequest {
  createUserRequest?: CreateUserRequest
}

export interface GetSinglePlayerGameRequest {
  gameId: string
}

export interface GetSinglePlayerGamesRequest {
  limit?: number
  sortBy?: GetSinglePlayerGamesSortByEnum
  orderBy?: GetSinglePlayerGamesOrderByEnum
}

export interface GetUserRequest {
  userId: string
}

export interface StartDailyChallengeGameRoundRequest {
  gameId: string
  roundNumber: number
}

export interface StartSinglePlayerGameRoundRequest {
  gameId: string
  roundNumber: number
}

export interface UpdateUserOperationRequest {
  updateUserRequest: UpdateUserRequest
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   * Create or resume today\'s daily challenge game
   */
  async createDailyChallengeGameRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateDailyChallengeGame200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/daily-challenge-games`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateDailyChallengeGame200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Create or resume today\'s daily challenge game
   */
  async createDailyChallengeGame(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateDailyChallengeGame200Response> {
    const response = await this.createDailyChallengeGameRaw(initOverrides)
    return await response.value()
  }

  /**
   * Complete a daily challenge round with a guess or timeout
   */
  async createDailyChallengeGameGuessRaw(
    requestParameters: CreateDailyChallengeGameGuessOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateDailyChallengeGameGuess200Response>> {
    if (requestParameters['gameId'] == null) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter "gameId" was null or undefined when calling createDailyChallengeGameGuess().',
      )
    }

    if (requestParameters['roundNumber'] == null) {
      throw new runtime.RequiredError(
        'roundNumber',
        'Required parameter "roundNumber" was null or undefined when calling createDailyChallengeGameGuess().',
      )
    }

    if (requestParameters['createDailyChallengeGameGuessRequest'] == null) {
      throw new runtime.RequiredError(
        'createDailyChallengeGameGuessRequest',
        'Required parameter "createDailyChallengeGameGuessRequest" was null or undefined when calling createDailyChallengeGameGuess().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/daily-challenge-games/{gameId}/rounds/{roundNumber}/guesses`
    urlPath = urlPath.replace(
      `{${'gameId'}}`,
      encodeURIComponent(String(requestParameters['gameId'])),
    )
    urlPath = urlPath.replace(
      `{${'roundNumber'}}`,
      encodeURIComponent(String(requestParameters['roundNumber'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateDailyChallengeGameGuessRequestToJSON(
          requestParameters['createDailyChallengeGameGuessRequest'],
        ),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateDailyChallengeGameGuess200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Complete a daily challenge round with a guess or timeout
   */
  async createDailyChallengeGameGuess(
    requestParameters: CreateDailyChallengeGameGuessOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateDailyChallengeGameGuess200Response> {
    const response = await this.createDailyChallengeGameGuessRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Create a single-player game
   */
  async createSinglePlayerGameRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateSinglePlayerGame201Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/single-player-games`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateSinglePlayerGame201ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Create a single-player game
   */
  async createSinglePlayerGame(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateSinglePlayerGame201Response> {
    const response = await this.createSinglePlayerGameRaw(initOverrides)
    return await response.value()
  }

  /**
   * Complete a single-player round with a guess or timeout
   */
  async createSinglePlayerGameGuessRaw(
    requestParameters: CreateSinglePlayerGameGuessOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateSinglePlayerGameGuess200Response>> {
    if (requestParameters['gameId'] == null) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter "gameId" was null or undefined when calling createSinglePlayerGameGuess().',
      )
    }

    if (requestParameters['roundNumber'] == null) {
      throw new runtime.RequiredError(
        'roundNumber',
        'Required parameter "roundNumber" was null or undefined when calling createSinglePlayerGameGuess().',
      )
    }

    if (requestParameters['createSinglePlayerGameGuessRequest'] == null) {
      throw new runtime.RequiredError(
        'createSinglePlayerGameGuessRequest',
        'Required parameter "createSinglePlayerGameGuessRequest" was null or undefined when calling createSinglePlayerGameGuess().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/single-player-games/{gameId}/rounds/{roundNumber}/guesses`
    urlPath = urlPath.replace(
      `{${'gameId'}}`,
      encodeURIComponent(String(requestParameters['gameId'])),
    )
    urlPath = urlPath.replace(
      `{${'roundNumber'}}`,
      encodeURIComponent(String(requestParameters['roundNumber'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateSinglePlayerGameGuessRequestToJSON(
          requestParameters['createSinglePlayerGameGuessRequest'],
        ),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateSinglePlayerGameGuess200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Complete a single-player round with a guess or timeout
   */
  async createSinglePlayerGameGuess(
    requestParameters: CreateSinglePlayerGameGuessOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateSinglePlayerGameGuess200Response> {
    const response = await this.createSinglePlayerGameGuessRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Create the current user if needed
   */
  async createUserRaw(
    requestParameters: CreateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateUser200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/me`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateUserRequestToJSON(requestParameters['createUserRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Create the current user if needed
   */
  async createUser(
    requestParameters: CreateUserOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateUser200Response> {
    const response = await this.createUserRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Delete the current user
   */
  async deleteUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/me`

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.VoidApiResponse(response)
  }

  /**
   * Delete the current user
   */
  async deleteUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
    await this.deleteUserRaw(initOverrides)
  }

  /**
   * Get the current user
   */
  async getCurrentUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetCurrentUser200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/me`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetCurrentUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get the current user
   */
  async getCurrentUser(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetCurrentUser200Response> {
    const response = await this.getCurrentUserRaw(initOverrides)
    return await response.value()
  }

  /**
   * Get an owned single-player game
   */
  async getSinglePlayerGameRaw(
    requestParameters: GetSinglePlayerGameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateSinglePlayerGame201Response>> {
    if (requestParameters['gameId'] == null) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter "gameId" was null or undefined when calling getSinglePlayerGame().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/single-player-games/{gameId}`
    urlPath = urlPath.replace(
      `{${'gameId'}}`,
      encodeURIComponent(String(requestParameters['gameId'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateSinglePlayerGame201ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get an owned single-player game
   */
  async getSinglePlayerGame(
    requestParameters: GetSinglePlayerGameRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateSinglePlayerGame201Response> {
    const response = await this.getSinglePlayerGameRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * List the current user\'s completed single-player games
   */
  async getSinglePlayerGamesRaw(
    requestParameters: GetSinglePlayerGamesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<GetSinglePlayerGames200ResponseInner>>> {
    const queryParameters: any = {}

    if (requestParameters['limit'] != null) {
      queryParameters['limit'] = requestParameters['limit']
    }

    if (requestParameters['sortBy'] != null) {
      queryParameters['sort_by'] = requestParameters['sortBy']
    }

    if (requestParameters['orderBy'] != null) {
      queryParameters['order_by'] = requestParameters['orderBy']
    }

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/single-player-games`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(GetSinglePlayerGames200ResponseInnerFromJSON),
    )
  }

  /**
   * List the current user\'s completed single-player games
   */
  async getSinglePlayerGames(
    requestParameters: GetSinglePlayerGamesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<GetSinglePlayerGames200ResponseInner>> {
    const response = await this.getSinglePlayerGamesRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Get today\'s daily challenge availability and attempt
   */
  async getTodayDailyChallengeRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetTodayDailyChallenge200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/daily-challenge-games/today`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetTodayDailyChallenge200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get today\'s daily challenge availability and attempt
   */
  async getTodayDailyChallenge(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetTodayDailyChallenge200Response> {
    const response = await this.getTodayDailyChallengeRaw(initOverrides)
    return await response.value()
  }

  /**
   * Get a user profile
   */
  async getUserRaw(
    requestParameters: GetUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetUser200Response>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getUser().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/{userId}`
    urlPath = urlPath.replace(
      `{${'userId'}}`,
      encodeURIComponent(String(requestParameters['userId'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Get a user profile
   */
  async getUser(
    requestParameters: GetUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetUser200Response> {
    const response = await this.getUserRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Start the next daily challenge round
   */
  async startDailyChallengeGameRoundRaw(
    requestParameters: StartDailyChallengeGameRoundRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StartDailyChallengeGameRound200Response>> {
    if (requestParameters['gameId'] == null) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter "gameId" was null or undefined when calling startDailyChallengeGameRound().',
      )
    }

    if (requestParameters['roundNumber'] == null) {
      throw new runtime.RequiredError(
        'roundNumber',
        'Required parameter "roundNumber" was null or undefined when calling startDailyChallengeGameRound().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/daily-challenge-games/{gameId}/rounds/{roundNumber}/start`
    urlPath = urlPath.replace(
      `{${'gameId'}}`,
      encodeURIComponent(String(requestParameters['gameId'])),
    )
    urlPath = urlPath.replace(
      `{${'roundNumber'}}`,
      encodeURIComponent(String(requestParameters['roundNumber'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      StartDailyChallengeGameRound200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Start the next daily challenge round
   */
  async startDailyChallengeGameRound(
    requestParameters: StartDailyChallengeGameRoundRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StartDailyChallengeGameRound200Response> {
    const response = await this.startDailyChallengeGameRoundRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Start the next single-player round
   */
  async startSinglePlayerGameRoundRaw(
    requestParameters: StartSinglePlayerGameRoundRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<StartSinglePlayerGameRound200Response>> {
    if (requestParameters['gameId'] == null) {
      throw new runtime.RequiredError(
        'gameId',
        'Required parameter "gameId" was null or undefined when calling startSinglePlayerGameRound().',
      )
    }

    if (requestParameters['roundNumber'] == null) {
      throw new runtime.RequiredError(
        'roundNumber',
        'Required parameter "roundNumber" was null or undefined when calling startSinglePlayerGameRound().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/single-player-games/{gameId}/rounds/{roundNumber}/start`
    urlPath = urlPath.replace(
      `{${'gameId'}}`,
      encodeURIComponent(String(requestParameters['gameId'])),
    )
    urlPath = urlPath.replace(
      `{${'roundNumber'}}`,
      encodeURIComponent(String(requestParameters['roundNumber'])),
    )

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      StartSinglePlayerGameRound200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Start the next single-player round
   */
  async startSinglePlayerGameRound(
    requestParameters: StartSinglePlayerGameRoundRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<StartSinglePlayerGameRound200Response> {
    const response = await this.startSinglePlayerGameRoundRaw(requestParameters, initOverrides)
    return await response.value()
  }

  /**
   * Update the current user
   */
  async updateUserRaw(
    requestParameters: UpdateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UpdateUser200Response>> {
    if (requestParameters['updateUserRequest'] == null) {
      throw new runtime.RequiredError(
        'updateUserRequest',
        'Required parameter "updateUserRequest" was null or undefined when calling updateUser().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken
      const tokenString = await token('BearerAuth', [])

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`
      }
    }

    let urlPath = `/api/v1/users/me`

    const response = await this.request(
      {
        path: urlPath,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: UpdateUserRequestToJSON(requestParameters['updateUserRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UpdateUser200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Update the current user
   */
  async updateUser(
    requestParameters: UpdateUserOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UpdateUser200Response> {
    const response = await this.updateUserRaw(requestParameters, initOverrides)
    return await response.value()
  }
}

/**
 * @export
 */
export const GetSinglePlayerGamesSortByEnum = {
  CreatedAt: 'created_at',
  CompletedAt: 'completed_at',
} as const
export type GetSinglePlayerGamesSortByEnum =
  (typeof GetSinglePlayerGamesSortByEnum)[keyof typeof GetSinglePlayerGamesSortByEnum]
/**
 * @export
 */
export const GetSinglePlayerGamesOrderByEnum = {
  Asc: 'asc',
  Desc: 'desc',
} as const
export type GetSinglePlayerGamesOrderByEnum =
  (typeof GetSinglePlayerGamesOrderByEnum)[keyof typeof GetSinglePlayerGamesOrderByEnum]
