/* tslint:disable */
/* eslint-disable */
/**
 * Geoguess Lite
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { GetHealth200Response } from '../models/index'
import { GetHealth200ResponseFromJSON, GetHealth200ResponseToJSON } from '../models/index'

/**
 *
 */
export class HealthApi extends runtime.BaseAPI {
  /**
   * Health check
   */
  async getHealthRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetHealth200Response>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    let urlPath = `/api/v1/health`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetHealth200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Health check
   */
  async getHealth(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetHealth200Response> {
    const response = await this.getHealthRaw(initOverrides)
    return await response.value()
  }
}
