/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "CleanupDailyChallenges": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CleanupSinglePlayerGames": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CleanupWithFriendsGames": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CreateDailyChallenge": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WithFriendsRoundAdvance": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WithFriendsRoundAdvanceDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WithFriendsRoundAdvanceWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "WithFriendsRoundTimeout": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WithFriendsRoundTimeoutDLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WithFriendsRoundTimeoutWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}

import "sst"
export {}