# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class Api:
        type: str
        url: str
    class App:
        name: str
        stage: str
    class CleanupDailyChallenges:
        name: str
        type: str
    class CleanupSinglePlayerGames:
        name: str
        type: str
    class CleanupWithFriendsGames:
        name: str
        type: str
    class CreateDailyChallenge:
        name: str
        type: str
    class WithFriendsGameStart:
        type: str
        url: str
    class WithFriendsGameStartDLQ:
        type: str
        url: str
    class WithFriendsGameStartWorker:
        name: str
        type: str
    class WithFriendsRoundAdvance:
        type: str
        url: str
    class WithFriendsRoundAdvanceDLQ:
        type: str
        url: str
    class WithFriendsRoundAdvanceWorker:
        name: str
        type: str
    class WithFriendsRoundTimeout:
        type: str
        url: str
    class WithFriendsRoundTimeoutDLQ:
        type: str
        url: str
    class WithFriendsRoundTimeoutWorker:
        name: str
        type: str

