openapi: 3.1.1
info:
  title: Geoguess Lite
  version: "1.0.0"
paths:
  /api/v1/health:
    $ref: ./paths/api/v1/health.yml
components:
  schemas:
    GetHealthResponse:
      $ref: ./components/schemas/get-health-response.yml
