openapi: 3.1.1
info:
  title: GeoGuessLite
  version: "1.0.0"
paths:
  /api/v1/health:
    $ref: ./paths/api/v1/health.yml
  /api/v1/single-player-games:
    $ref: ./paths/api/v1/single-player-games/index.yml
  /api/v1/single-player-games/{gameId}:
    $ref: ./paths/api/v1/single-player-games/game-by-id.yml
  /api/v1/single-player-games/{gameId}/rounds/{roundNumber}/start:
    $ref: ./paths/api/v1/single-player-games/round-start.yml
  /api/v1/single-player-games/{gameId}/rounds/{roundNumber}/guesses:
    $ref: ./paths/api/v1/single-player-games/guesses.yml
  /api/v1/daily-challenge-games:
    $ref: ./paths/api/v1/daily-challenge-games/index.yml
  /api/v1/daily-challenge-games/today:
    $ref: ./paths/api/v1/daily-challenge-games/today.yml
  /api/v1/daily-challenge-games/{gameId}/rounds/{roundNumber}/start:
    $ref: ./paths/api/v1/daily-challenge-games/round-start.yml
  /api/v1/daily-challenge-games/{gameId}/rounds/{roundNumber}/guesses:
    $ref: ./paths/api/v1/daily-challenge-games/guesses.yml
  /api/v1/users/me:
    $ref: ./paths/api/v1/users/me.yml
  /api/v1/users/{userId}:
    $ref: ./paths/api/v1/users/user-by-id.yml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Firebase ID token
  schemas:
    CreateDailyChallengeGameResponse:
      $ref: ./components/schemas/create-daily-challenge-game-response.yml
    CreateDailyChallengeGameGuessRequest:
      $ref: ./components/schemas/create-daily-challenge-game-guess-request.yml
    CreateDailyChallengeGameGuessResponse:
      $ref: ./components/schemas/create-daily-challenge-game-guess-response.yml
    CreateSinglePlayerGameResponse:
      $ref: ./components/schemas/create-single-player-game-response.yml
    CreateSinglePlayerGameGuessRequest:
      $ref: ./components/schemas/create-single-player-game-guess-request.yml
    CreateSinglePlayerGameGuessCoordinate:
      $ref: ./components/schemas/create-single-player-game-guess-coordinate.yml
    CreateSinglePlayerGameGuessResponse:
      $ref: ./components/schemas/create-single-player-game-guess-response.yml
    CreateUserRequest:
      $ref: ./components/schemas/create-user-request.yml
    CreateUserResponse:
      $ref: ./components/schemas/create-user-response.yml
    ErrorResponse:
      $ref: ./components/schemas/error-response.yml
    GetCurrentUserResponse:
      $ref: ./components/schemas/get-current-user-response.yml
    GetHealthResponse:
      $ref: ./components/schemas/get-health-response.yml
    GetSinglePlayerGameResponse:
      $ref: ./components/schemas/get-single-player-game-response.yml
    GetSinglePlayerGamesResponse:
      $ref: ./components/schemas/get-single-player-games-response.yml
    GetUserResponse:
      $ref: ./components/schemas/get-user-response.yml
    UpdateUserRequest:
      $ref: ./components/schemas/update-user-request.yml
    UpdateUserCountry:
      $ref: ./components/schemas/update-user-country.yml
    UpdateUserResponse:
      $ref: ./components/schemas/update-user-response.yml
    StartSinglePlayerGameRoundResponse:
      $ref: ./components/schemas/start-single-player-game-round-response.yml
    StartDailyChallengeGameRoundResponse:
      $ref: ./components/schemas/start-daily-challenge-game-round-response.yml
    GetTodayDailyChallengeResponse:
      $ref: ./components/schemas/get-today-daily-challenge-response.yml
